// File: CMP_Multiplier.v
// Generated by MyHDL 0.11
// Date: Sun Sep  5 16:22:05 2021


`timescale 1ns/10ps

module CMP_Multiplier (
    OUTS,
    A,
    B
);


output [44:0] OUTS;
wire [44:0] OUTS;
input [11:0] A;
input [11:0] B;

wire [143:0] OutBits_ppg;
wire [143:0] PPG0_outs_vec;
wire [0:0] PPG0_AND0_out;
wire [0:0] PPG0_AND1_out;
wire [0:0] PPG0_AND2_out;
wire [0:0] PPG0_AND3_out;
wire [0:0] PPG0_AND4_out;
wire [0:0] PPG0_AND5_out;
wire [0:0] PPG0_AND6_out;
wire [0:0] PPG0_AND7_out;
wire [0:0] PPG0_AND8_out;
wire [0:0] PPG0_AND9_out;
wire [0:0] PPG0_AND10_out;
wire [0:0] PPG0_AND11_out;
wire [0:0] PPG0_AND12_out;
wire [0:0] PPG0_AND13_out;
wire [0:0] PPG0_AND14_out;
wire [0:0] PPG0_AND15_out;
wire [0:0] PPG0_AND16_out;
wire [0:0] PPG0_AND17_out;
wire [0:0] PPG0_AND18_out;
wire [0:0] PPG0_AND19_out;
wire [0:0] PPG0_AND20_out;
wire [0:0] PPG0_AND21_out;
wire [0:0] PPG0_AND22_out;
wire [0:0] PPG0_AND23_out;
wire [0:0] PPG0_AND24_out;
wire [0:0] PPG0_AND25_out;
wire [0:0] PPG0_AND26_out;
wire [0:0] PPG0_AND27_out;
wire [0:0] PPG0_AND28_out;
wire [0:0] PPG0_AND29_out;
wire [0:0] PPG0_AND30_out;
wire [0:0] PPG0_AND31_out;
wire [0:0] PPG0_AND32_out;
wire [0:0] PPG0_AND33_out;
wire [0:0] PPG0_AND34_out;
wire [0:0] PPG0_AND35_out;
wire [0:0] PPG0_AND36_out;
wire [0:0] PPG0_AND37_out;
wire [0:0] PPG0_AND38_out;
wire [0:0] PPG0_AND39_out;
wire [0:0] PPG0_AND40_out;
wire [0:0] PPG0_AND41_out;
wire [0:0] PPG0_AND42_out;
wire [0:0] PPG0_AND43_out;
wire [0:0] PPG0_AND44_out;
wire [0:0] PPG0_AND45_out;
wire [0:0] PPG0_AND46_out;
wire [0:0] PPG0_AND47_out;
wire [0:0] PPG0_AND48_out;
wire [0:0] PPG0_AND49_out;
wire [0:0] PPG0_AND50_out;
wire [0:0] PPG0_AND51_out;
wire [0:0] PPG0_AND52_out;
wire [0:0] PPG0_AND53_out;
wire [0:0] PPG0_AND54_out;
wire [0:0] PPG0_AND55_out;
wire [0:0] PPG0_AND56_out;
wire [0:0] PPG0_AND57_out;
wire [0:0] PPG0_AND58_out;
wire [0:0] PPG0_AND59_out;
wire [0:0] PPG0_AND60_out;
wire [0:0] PPG0_AND61_out;
wire [0:0] PPG0_AND62_out;
wire [0:0] PPG0_AND63_out;
wire [0:0] PPG0_AND64_out;
wire [0:0] PPG0_AND65_out;
wire [0:0] PPG0_AND66_out;
wire [0:0] PPG0_AND67_out;
wire [0:0] PPG0_AND68_out;
wire [0:0] PPG0_AND69_out;
wire [0:0] PPG0_AND70_out;
wire [0:0] PPG0_AND71_out;
wire [0:0] PPG0_AND72_out;
wire [0:0] PPG0_AND73_out;
wire [0:0] PPG0_AND74_out;
wire [0:0] PPG0_AND75_out;
wire [0:0] PPG0_AND76_out;
wire [0:0] PPG0_AND77_out;
wire [0:0] PPG0_AND78_out;
wire [0:0] PPG0_AND79_out;
wire [0:0] PPG0_AND80_out;
wire [0:0] PPG0_AND81_out;
wire [0:0] PPG0_AND82_out;
wire [0:0] PPG0_AND83_out;
wire [0:0] PPG0_AND84_out;
wire [0:0] PPG0_AND85_out;
wire [0:0] PPG0_AND86_out;
wire [0:0] PPG0_AND87_out;
wire [0:0] PPG0_AND88_out;
wire [0:0] PPG0_AND89_out;
wire [0:0] PPG0_AND90_out;
wire [0:0] PPG0_AND91_out;
wire [0:0] PPG0_AND92_out;
wire [0:0] PPG0_AND93_out;
wire [0:0] PPG0_AND94_out;
wire [0:0] PPG0_AND95_out;
wire [0:0] PPG0_AND96_out;
wire [0:0] PPG0_AND97_out;
wire [0:0] PPG0_AND98_out;
wire [0:0] PPG0_AND99_out;
wire [0:0] PPG0_AND100_out;
wire [0:0] PPG0_AND101_out;
wire [0:0] PPG0_AND102_out;
wire [0:0] PPG0_AND103_out;
wire [0:0] PPG0_AND104_out;
wire [0:0] PPG0_AND105_out;
wire [0:0] PPG0_AND106_out;
wire [0:0] PPG0_AND107_out;
wire [0:0] PPG0_AND108_out;
wire [0:0] PPG0_AND109_out;
wire [0:0] PPG0_AND110_out;
wire [0:0] PPG0_AND111_out;
wire [0:0] PPG0_AND112_out;
wire [0:0] PPG0_AND113_out;
wire [0:0] PPG0_AND114_out;
wire [0:0] PPG0_AND115_out;
wire [0:0] PPG0_AND116_out;
wire [0:0] PPG0_AND117_out;
wire [0:0] PPG0_AND118_out;
wire [0:0] PPG0_AND119_out;
wire [0:0] PPG0_AND120_out;
wire [0:0] PPG0_AND121_out;
wire [0:0] PPG0_AND122_out;
wire [0:0] PPG0_AND123_out;
wire [0:0] PPG0_AND124_out;
wire [0:0] PPG0_AND125_out;
wire [0:0] PPG0_AND126_out;
wire [0:0] PPG0_AND127_out;
wire [0:0] PPG0_AND128_out;
wire [0:0] PPG0_AND129_out;
wire [0:0] PPG0_AND130_out;
wire [0:0] PPG0_AND131_out;
wire [0:0] PPG0_AND132_out;
wire [0:0] PPG0_AND133_out;
wire [0:0] PPG0_AND134_out;
wire [0:0] PPG0_AND135_out;
wire [0:0] PPG0_AND136_out;
wire [0:0] PPG0_AND137_out;
wire [0:0] PPG0_AND138_out;
wire [0:0] PPG0_AND139_out;
wire [0:0] PPG0_AND140_out;
wire [0:0] PPG0_AND141_out;
wire [0:0] PPG0_AND142_out;
wire [0:0] PPG0_AND143_out;
wire [2:0] ISCAS180_col_inputs_vec;
wire [2:0] ISCAS180_vInputs;
wire [44:0] ISCAS180_outs_vec;
wire [1:0] ISCAS180_highorderAC0_OUTS;
wire [1:0] ISCAS180_highorderAC0_outs_vec;
wire [0:0] ISCAS180_highorderAC0_AC320_out1;
wire [0:0] ISCAS180_highorderAC0_AC320_out2;
wire [3:0] ISCAS180_slice_shadower1_INPUTS;
wire [3:0] ISCAS180_slice_shadower1_OUTS;
wire [1:0] ISCAS180_highorderAC1_OUTS;
wire [1:0] ISCAS180_highorderAC1_outs_vec;
wire [0:0] ISCAS180_highorderAC1_AC420_out1;
wire [0:0] ISCAS180_highorderAC1_AC420_out2;
wire [4:0] ISCAS180_slice_shadower2_INPUTS;
wire [4:0] ISCAS180_slice_shadower2_OUTS;
wire [2:0] ISCAS180_highorderAC2_OUTS;
wire [2:0] ISCAS180_highorderAC2_outs_vec;
wire [0:0] ISCAS180_highorderAC2_AC530_out1;
wire [0:0] ISCAS180_highorderAC2_AC530_out2;
wire [0:0] ISCAS180_highorderAC2_AC530_out3;
wire [5:0] ISCAS180_slice_shadower3_INPUTS;
wire [5:0] ISCAS180_slice_shadower3_OUTS;
wire [2:0] ISCAS180_highorderAC3_OUTS;
wire [2:0] ISCAS180_highorderAC3_outs_vec;
wire [0:0] ISCAS180_highorderAC3_AC630_out1;
wire [0:0] ISCAS180_highorderAC3_AC630_out2;
wire [0:0] ISCAS180_highorderAC3_AC630_out3;
wire [6:0] ISCAS180_slice_shadower4_INPUTS;
wire [6:0] ISCAS180_slice_shadower4_OUTS;
wire [3:0] ISCAS180_highorderAC4_OUTS;
wire [3:0] ISCAS180_highorderAC4_outs_vec;
wire [0:0] ISCAS180_highorderAC4_AC321_out1;
wire [0:0] ISCAS180_highorderAC4_AC321_out2;
wire [0:0] ISCAS180_highorderAC4_AC421_out1;
wire [0:0] ISCAS180_highorderAC4_AC421_out2;
wire [7:0] ISCAS180_slice_shadower5_INPUTS;
wire [7:0] ISCAS180_slice_shadower5_OUTS;
wire [3:0] ISCAS180_highorderAC5_OUTS;
wire [3:0] ISCAS180_highorderAC5_outs_vec;
wire [0:0] ISCAS180_highorderAC5_AC422_out1;
wire [0:0] ISCAS180_highorderAC5_AC422_out2;
wire [0:0] ISCAS180_highorderAC5_AC423_out1;
wire [0:0] ISCAS180_highorderAC5_AC423_out2;
wire [8:0] ISCAS180_slice_shadower6_INPUTS;
wire [8:0] ISCAS180_slice_shadower6_OUTS;
wire [4:0] ISCAS180_highorderAC6_OUTS;
wire [4:0] ISCAS180_highorderAC6_outs_vec;
wire [0:0] ISCAS180_highorderAC6_AC424_out1;
wire [0:0] ISCAS180_highorderAC6_AC424_out2;
wire [0:0] ISCAS180_highorderAC6_AC531_out1;
wire [0:0] ISCAS180_highorderAC6_AC531_out2;
wire [0:0] ISCAS180_highorderAC6_AC531_out3;
wire [9:0] ISCAS180_slice_shadower7_INPUTS;
wire [9:0] ISCAS180_slice_shadower7_OUTS;
wire [4:0] ISCAS180_highorderAC7_OUTS;
wire [4:0] ISCAS180_highorderAC7_outs_vec;
wire [0:0] ISCAS180_highorderAC7_AC425_out1;
wire [0:0] ISCAS180_highorderAC7_AC425_out2;
wire [0:0] ISCAS180_highorderAC7_AC631_out1;
wire [0:0] ISCAS180_highorderAC7_AC631_out2;
wire [0:0] ISCAS180_highorderAC7_AC631_out3;
wire [10:0] ISCAS180_slice_shadower8_INPUTS;
wire [10:0] ISCAS180_slice_shadower8_OUTS;
wire [5:0] ISCAS180_highorderAC8_OUTS;
wire [5:0] ISCAS180_highorderAC8_outs_vec;
wire [0:0] ISCAS180_highorderAC8_AC322_out1;
wire [0:0] ISCAS180_highorderAC8_AC322_out2;
wire [0:0] ISCAS180_highorderAC8_AC426_out1;
wire [0:0] ISCAS180_highorderAC8_AC426_out2;
wire [0:0] ISCAS180_highorderAC8_AC427_out1;
wire [0:0] ISCAS180_highorderAC8_AC427_out2;
wire [11:0] ISCAS180_slice_shadower9_INPUTS;
wire [11:0] ISCAS180_slice_shadower9_OUTS;
wire [5:0] ISCAS180_highorderAC9_OUTS;
wire [5:0] ISCAS180_highorderAC9_outs_vec;
wire [0:0] ISCAS180_highorderAC9_AC428_out1;
wire [0:0] ISCAS180_highorderAC9_AC428_out2;
wire [0:0] ISCAS180_highorderAC9_AC429_out1;
wire [0:0] ISCAS180_highorderAC9_AC429_out2;
wire [0:0] ISCAS180_highorderAC9_AC4210_out1;
wire [0:0] ISCAS180_highorderAC9_AC4210_out2;
wire [10:0] ISCAS180_slice_shadower10_INPUTS;
wire [10:0] ISCAS180_slice_shadower10_OUTS;
wire [5:0] ISCAS180_highorderAC10_OUTS;
wire [5:0] ISCAS180_highorderAC10_outs_vec;
wire [0:0] ISCAS180_highorderAC10_AC323_out1;
wire [0:0] ISCAS180_highorderAC10_AC323_out2;
wire [0:0] ISCAS180_highorderAC10_AC4211_out1;
wire [0:0] ISCAS180_highorderAC10_AC4211_out2;
wire [0:0] ISCAS180_highorderAC10_AC4212_out1;
wire [0:0] ISCAS180_highorderAC10_AC4212_out2;
wire [9:0] ISCAS180_slice_shadower11_INPUTS;
wire [9:0] ISCAS180_slice_shadower11_OUTS;
wire [4:0] ISCAS180_highorderAC11_OUTS;
wire [4:0] ISCAS180_highorderAC11_outs_vec;
wire [0:0] ISCAS180_highorderAC11_AC4213_out1;
wire [0:0] ISCAS180_highorderAC11_AC4213_out2;
wire [0:0] ISCAS180_highorderAC11_AC632_out1;
wire [0:0] ISCAS180_highorderAC11_AC632_out2;
wire [0:0] ISCAS180_highorderAC11_AC632_out3;
wire [8:0] ISCAS180_slice_shadower12_INPUTS;
wire [8:0] ISCAS180_slice_shadower12_OUTS;
wire [4:0] ISCAS180_highorderAC12_OUTS;
wire [4:0] ISCAS180_highorderAC12_outs_vec;
wire [0:0] ISCAS180_highorderAC12_AC4214_out1;
wire [0:0] ISCAS180_highorderAC12_AC4214_out2;
wire [0:0] ISCAS180_highorderAC12_AC532_out1;
wire [0:0] ISCAS180_highorderAC12_AC532_out2;
wire [0:0] ISCAS180_highorderAC12_AC532_out3;
wire [7:0] ISCAS180_slice_shadower13_INPUTS;
wire [7:0] ISCAS180_slice_shadower13_OUTS;
wire [3:0] ISCAS180_highorderAC13_OUTS;
wire [3:0] ISCAS180_highorderAC13_outs_vec;
wire [0:0] ISCAS180_highorderAC13_AC4215_out1;
wire [0:0] ISCAS180_highorderAC13_AC4215_out2;
wire [0:0] ISCAS180_highorderAC13_AC4216_out1;
wire [0:0] ISCAS180_highorderAC13_AC4216_out2;
wire [0:0] ISCAS180_FA0_cout;
wire [0:0] ISCAS180_FA0_sum;
wire [0:0] ISCAS180_FA1_cout;
wire [0:0] ISCAS180_FA1_sum;
wire [0:0] ISCAS180_FA2_cout;
wire [0:0] ISCAS180_FA2_sum;
wire [0:0] ISCAS180_FA3_cout;
wire [0:0] ISCAS180_FA3_sum;
wire [0:0] ISCAS180_FA4_cout;
wire [0:0] ISCAS180_FA4_sum;
wire [0:0] ISCAS180_FA5_cout;
wire [0:0] ISCAS180_FA5_sum;
wire [0:0] ISCAS180_FA6_cout;
wire [0:0] ISCAS180_FA6_sum;
wire [0:0] ISCAS180_FA7_cout;
wire [0:0] ISCAS180_FA7_sum;
wire [0:0] ISCAS180_FA8_cout;
wire [0:0] ISCAS180_FA8_sum;
wire [0:0] ISCAS180_FA9_cout;
wire [0:0] ISCAS180_FA9_sum;
wire [2:0] ISCAS180_slice_shadower14_INPUTS;
wire [2:0] ISCAS180_slice_shadower14_OUTS;
wire [1:0] ISCAS180_highorderAC14_OUTS;
wire [1:0] ISCAS180_highorderAC14_outs_vec;
wire [0:0] ISCAS180_highorderAC14_AC324_out1;
wire [0:0] ISCAS180_highorderAC14_AC324_out2;
wire [2:0] ISCAS180_slice_shadower15_INPUTS;
wire [2:0] ISCAS180_slice_shadower15_OUTS;
wire [1:0] ISCAS180_highorderAC15_OUTS;
wire [1:0] ISCAS180_highorderAC15_outs_vec;
wire [0:0] ISCAS180_highorderAC15_AC325_out1;
wire [0:0] ISCAS180_highorderAC15_AC325_out2;
wire [3:0] ISCAS180_slice_shadower16_INPUTS;
wire [3:0] ISCAS180_slice_shadower16_OUTS;
wire [1:0] ISCAS180_highorderAC16_OUTS;
wire [1:0] ISCAS180_highorderAC16_outs_vec;
wire [0:0] ISCAS180_highorderAC16_AC4217_out1;
wire [0:0] ISCAS180_highorderAC16_AC4217_out2;
wire [3:0] ISCAS180_slice_shadower17_INPUTS;
wire [3:0] ISCAS180_slice_shadower17_OUTS;
wire [1:0] ISCAS180_highorderAC17_OUTS;
wire [1:0] ISCAS180_highorderAC17_outs_vec;
wire [0:0] ISCAS180_highorderAC17_AC4218_out1;
wire [0:0] ISCAS180_highorderAC17_AC4218_out2;
wire [4:0] ISCAS180_slice_shadower18_INPUTS;
wire [4:0] ISCAS180_slice_shadower18_OUTS;
wire [2:0] ISCAS180_highorderAC18_OUTS;
wire [2:0] ISCAS180_highorderAC18_outs_vec;
wire [0:0] ISCAS180_highorderAC18_AC533_out1;
wire [0:0] ISCAS180_highorderAC18_AC533_out2;
wire [0:0] ISCAS180_highorderAC18_AC533_out3;
wire [4:0] ISCAS180_slice_shadower19_INPUTS;
wire [4:0] ISCAS180_slice_shadower19_OUTS;
wire [2:0] ISCAS180_highorderAC19_OUTS;
wire [2:0] ISCAS180_highorderAC19_outs_vec;
wire [0:0] ISCAS180_highorderAC19_AC534_out1;
wire [0:0] ISCAS180_highorderAC19_AC534_out2;
wire [0:0] ISCAS180_highorderAC19_AC534_out3;
wire [5:0] ISCAS180_slice_shadower20_INPUTS;
wire [5:0] ISCAS180_slice_shadower20_OUTS;
wire [2:0] ISCAS180_highorderAC20_OUTS;
wire [2:0] ISCAS180_highorderAC20_outs_vec;
wire [0:0] ISCAS180_highorderAC20_AC633_out1;
wire [0:0] ISCAS180_highorderAC20_AC633_out2;
wire [0:0] ISCAS180_highorderAC20_AC633_out3;
wire [5:0] ISCAS180_slice_shadower21_INPUTS;
wire [5:0] ISCAS180_slice_shadower21_OUTS;
wire [2:0] ISCAS180_highorderAC21_OUTS;
wire [2:0] ISCAS180_highorderAC21_outs_vec;
wire [0:0] ISCAS180_highorderAC21_AC634_out1;
wire [0:0] ISCAS180_highorderAC21_AC634_out2;
wire [0:0] ISCAS180_highorderAC21_AC634_out3;
wire [5:0] ISCAS180_slice_shadower22_INPUTS;
wire [5:0] ISCAS180_slice_shadower22_OUTS;
wire [2:0] ISCAS180_highorderAC22_OUTS;
wire [2:0] ISCAS180_highorderAC22_outs_vec;
wire [0:0] ISCAS180_highorderAC22_AC635_out1;
wire [0:0] ISCAS180_highorderAC22_AC635_out2;
wire [0:0] ISCAS180_highorderAC22_AC635_out3;
wire [4:0] ISCAS180_slice_shadower23_INPUTS;
wire [4:0] ISCAS180_slice_shadower23_OUTS;
wire [2:0] ISCAS180_highorderAC23_OUTS;
wire [2:0] ISCAS180_highorderAC23_outs_vec;
wire [0:0] ISCAS180_highorderAC23_AC535_out1;
wire [0:0] ISCAS180_highorderAC23_AC535_out2;
wire [0:0] ISCAS180_highorderAC23_AC535_out3;
wire [4:0] ISCAS180_slice_shadower24_INPUTS;
wire [4:0] ISCAS180_slice_shadower24_OUTS;
wire [2:0] ISCAS180_highorderAC24_OUTS;
wire [2:0] ISCAS180_highorderAC24_outs_vec;
wire [0:0] ISCAS180_highorderAC24_AC536_out1;
wire [0:0] ISCAS180_highorderAC24_AC536_out2;
wire [0:0] ISCAS180_highorderAC24_AC536_out3;
wire [3:0] ISCAS180_slice_shadower25_INPUTS;
wire [3:0] ISCAS180_slice_shadower25_OUTS;
wire [1:0] ISCAS180_highorderAC25_OUTS;
wire [1:0] ISCAS180_highorderAC25_outs_vec;
wire [0:0] ISCAS180_highorderAC25_AC4219_out1;
wire [0:0] ISCAS180_highorderAC25_AC4219_out2;
wire [0:0] ISCAS180_HA0_cout;
wire [0:0] ISCAS180_HA0_sum;
wire [0:0] ISCAS180_HA1_cout;
wire [0:0] ISCAS180_HA1_sum;
wire [0:0] ISCAS180_HA2_cout;
wire [0:0] ISCAS180_HA2_sum;
wire [0:0] ISCAS180_FA10_cout;
wire [0:0] ISCAS180_FA10_sum;
wire [0:0] ISCAS180_FA11_cout;
wire [0:0] ISCAS180_FA11_sum;
wire [0:0] ISCAS180_FA12_cout;
wire [0:0] ISCAS180_FA12_sum;
wire [0:0] ISCAS180_FA13_cout;
wire [0:0] ISCAS180_FA13_sum;
wire [0:0] ISCAS180_FA14_cout;
wire [0:0] ISCAS180_FA14_sum;
wire [0:0] ISCAS180_FA15_cout;
wire [0:0] ISCAS180_FA15_sum;
wire [0:0] ISCAS180_HA3_cout;
wire [0:0] ISCAS180_HA3_sum;
wire [0:0] ISCAS180_FA16_cout;
wire [0:0] ISCAS180_FA16_sum;
wire [0:0] ISCAS180_FA17_cout;
wire [0:0] ISCAS180_FA17_sum;
wire [0:0] ISCAS180_FA18_cout;
wire [0:0] ISCAS180_FA18_sum;
wire [0:0] ISCAS180_FA19_cout;
wire [0:0] ISCAS180_FA19_sum;
wire [0:0] ISCAS180_FA20_cout;
wire [0:0] ISCAS180_FA20_sum;

assign PPG0_outs_vec[143] = PPG0_AND143_out[0];
assign PPG0_outs_vec[142] = PPG0_AND141_out[0];
assign PPG0_outs_vec[141] = PPG0_AND142_out[0];
assign PPG0_outs_vec[140] = PPG0_AND138_out[0];
assign PPG0_outs_vec[139] = PPG0_AND139_out[0];
assign PPG0_outs_vec[138] = PPG0_AND140_out[0];
assign PPG0_outs_vec[137] = PPG0_AND134_out[0];
assign PPG0_outs_vec[136] = PPG0_AND135_out[0];
assign PPG0_outs_vec[135] = PPG0_AND136_out[0];
assign PPG0_outs_vec[134] = PPG0_AND137_out[0];
assign PPG0_outs_vec[133] = PPG0_AND129_out[0];
assign PPG0_outs_vec[132] = PPG0_AND130_out[0];
assign PPG0_outs_vec[131] = PPG0_AND131_out[0];
assign PPG0_outs_vec[130] = PPG0_AND132_out[0];
assign PPG0_outs_vec[129] = PPG0_AND133_out[0];
assign PPG0_outs_vec[128] = PPG0_AND123_out[0];
assign PPG0_outs_vec[127] = PPG0_AND124_out[0];
assign PPG0_outs_vec[126] = PPG0_AND125_out[0];
assign PPG0_outs_vec[125] = PPG0_AND126_out[0];
assign PPG0_outs_vec[124] = PPG0_AND127_out[0];
assign PPG0_outs_vec[123] = PPG0_AND128_out[0];
assign PPG0_outs_vec[122] = PPG0_AND116_out[0];
assign PPG0_outs_vec[121] = PPG0_AND117_out[0];
assign PPG0_outs_vec[120] = PPG0_AND118_out[0];
assign PPG0_outs_vec[119] = PPG0_AND119_out[0];
assign PPG0_outs_vec[118] = PPG0_AND120_out[0];
assign PPG0_outs_vec[117] = PPG0_AND121_out[0];
assign PPG0_outs_vec[116] = PPG0_AND122_out[0];
assign PPG0_outs_vec[115] = PPG0_AND108_out[0];
assign PPG0_outs_vec[114] = PPG0_AND109_out[0];
assign PPG0_outs_vec[113] = PPG0_AND110_out[0];
assign PPG0_outs_vec[112] = PPG0_AND111_out[0];
assign PPG0_outs_vec[111] = PPG0_AND112_out[0];
assign PPG0_outs_vec[110] = PPG0_AND113_out[0];
assign PPG0_outs_vec[109] = PPG0_AND114_out[0];
assign PPG0_outs_vec[108] = PPG0_AND115_out[0];
assign PPG0_outs_vec[107] = PPG0_AND99_out[0];
assign PPG0_outs_vec[106] = PPG0_AND100_out[0];
assign PPG0_outs_vec[105] = PPG0_AND101_out[0];
assign PPG0_outs_vec[104] = PPG0_AND102_out[0];
assign PPG0_outs_vec[103] = PPG0_AND103_out[0];
assign PPG0_outs_vec[102] = PPG0_AND104_out[0];
assign PPG0_outs_vec[101] = PPG0_AND105_out[0];
assign PPG0_outs_vec[100] = PPG0_AND106_out[0];
assign PPG0_outs_vec[99] = PPG0_AND107_out[0];
assign PPG0_outs_vec[98] = PPG0_AND89_out[0];
assign PPG0_outs_vec[97] = PPG0_AND90_out[0];
assign PPG0_outs_vec[96] = PPG0_AND91_out[0];
assign PPG0_outs_vec[95] = PPG0_AND92_out[0];
assign PPG0_outs_vec[94] = PPG0_AND93_out[0];
assign PPG0_outs_vec[93] = PPG0_AND94_out[0];
assign PPG0_outs_vec[92] = PPG0_AND95_out[0];
assign PPG0_outs_vec[91] = PPG0_AND96_out[0];
assign PPG0_outs_vec[90] = PPG0_AND97_out[0];
assign PPG0_outs_vec[89] = PPG0_AND98_out[0];
assign PPG0_outs_vec[88] = PPG0_AND78_out[0];
assign PPG0_outs_vec[87] = PPG0_AND79_out[0];
assign PPG0_outs_vec[86] = PPG0_AND80_out[0];
assign PPG0_outs_vec[85] = PPG0_AND81_out[0];
assign PPG0_outs_vec[84] = PPG0_AND82_out[0];
assign PPG0_outs_vec[83] = PPG0_AND83_out[0];
assign PPG0_outs_vec[82] = PPG0_AND84_out[0];
assign PPG0_outs_vec[81] = PPG0_AND85_out[0];
assign PPG0_outs_vec[80] = PPG0_AND86_out[0];
assign PPG0_outs_vec[79] = PPG0_AND87_out[0];
assign PPG0_outs_vec[78] = PPG0_AND88_out[0];
assign PPG0_outs_vec[77] = PPG0_AND66_out[0];
assign PPG0_outs_vec[76] = PPG0_AND67_out[0];
assign PPG0_outs_vec[75] = PPG0_AND68_out[0];
assign PPG0_outs_vec[74] = PPG0_AND69_out[0];
assign PPG0_outs_vec[73] = PPG0_AND70_out[0];
assign PPG0_outs_vec[72] = PPG0_AND71_out[0];
assign PPG0_outs_vec[71] = PPG0_AND72_out[0];
assign PPG0_outs_vec[70] = PPG0_AND73_out[0];
assign PPG0_outs_vec[69] = PPG0_AND74_out[0];
assign PPG0_outs_vec[68] = PPG0_AND75_out[0];
assign PPG0_outs_vec[67] = PPG0_AND76_out[0];
assign PPG0_outs_vec[66] = PPG0_AND77_out[0];
assign PPG0_outs_vec[65] = PPG0_AND55_out[0];
assign PPG0_outs_vec[64] = PPG0_AND56_out[0];
assign PPG0_outs_vec[63] = PPG0_AND57_out[0];
assign PPG0_outs_vec[62] = PPG0_AND58_out[0];
assign PPG0_outs_vec[61] = PPG0_AND59_out[0];
assign PPG0_outs_vec[60] = PPG0_AND60_out[0];
assign PPG0_outs_vec[59] = PPG0_AND61_out[0];
assign PPG0_outs_vec[58] = PPG0_AND62_out[0];
assign PPG0_outs_vec[57] = PPG0_AND63_out[0];
assign PPG0_outs_vec[56] = PPG0_AND64_out[0];
assign PPG0_outs_vec[55] = PPG0_AND65_out[0];
assign PPG0_outs_vec[54] = PPG0_AND45_out[0];
assign PPG0_outs_vec[53] = PPG0_AND46_out[0];
assign PPG0_outs_vec[52] = PPG0_AND47_out[0];
assign PPG0_outs_vec[51] = PPG0_AND48_out[0];
assign PPG0_outs_vec[50] = PPG0_AND49_out[0];
assign PPG0_outs_vec[49] = PPG0_AND50_out[0];
assign PPG0_outs_vec[48] = PPG0_AND51_out[0];
assign PPG0_outs_vec[47] = PPG0_AND52_out[0];
assign PPG0_outs_vec[46] = PPG0_AND53_out[0];
assign PPG0_outs_vec[45] = PPG0_AND54_out[0];
assign PPG0_outs_vec[44] = PPG0_AND36_out[0];
assign PPG0_outs_vec[43] = PPG0_AND37_out[0];
assign PPG0_outs_vec[42] = PPG0_AND38_out[0];
assign PPG0_outs_vec[41] = PPG0_AND39_out[0];
assign PPG0_outs_vec[40] = PPG0_AND40_out[0];
assign PPG0_outs_vec[39] = PPG0_AND41_out[0];
assign PPG0_outs_vec[38] = PPG0_AND42_out[0];
assign PPG0_outs_vec[37] = PPG0_AND43_out[0];
assign PPG0_outs_vec[36] = PPG0_AND44_out[0];
assign PPG0_outs_vec[35] = PPG0_AND28_out[0];
assign PPG0_outs_vec[34] = PPG0_AND29_out[0];
assign PPG0_outs_vec[33] = PPG0_AND30_out[0];
assign PPG0_outs_vec[32] = PPG0_AND31_out[0];
assign PPG0_outs_vec[31] = PPG0_AND32_out[0];
assign PPG0_outs_vec[30] = PPG0_AND33_out[0];
assign PPG0_outs_vec[29] = PPG0_AND34_out[0];
assign PPG0_outs_vec[28] = PPG0_AND35_out[0];
assign PPG0_outs_vec[27] = PPG0_AND21_out[0];
assign PPG0_outs_vec[26] = PPG0_AND22_out[0];
assign PPG0_outs_vec[25] = PPG0_AND23_out[0];
assign PPG0_outs_vec[24] = PPG0_AND24_out[0];
assign PPG0_outs_vec[23] = PPG0_AND25_out[0];
assign PPG0_outs_vec[22] = PPG0_AND26_out[0];
assign PPG0_outs_vec[21] = PPG0_AND27_out[0];
assign PPG0_outs_vec[20] = PPG0_AND15_out[0];
assign PPG0_outs_vec[19] = PPG0_AND16_out[0];
assign PPG0_outs_vec[18] = PPG0_AND17_out[0];
assign PPG0_outs_vec[17] = PPG0_AND18_out[0];
assign PPG0_outs_vec[16] = PPG0_AND19_out[0];
assign PPG0_outs_vec[15] = PPG0_AND20_out[0];
assign PPG0_outs_vec[14] = PPG0_AND10_out[0];
assign PPG0_outs_vec[13] = PPG0_AND11_out[0];
assign PPG0_outs_vec[12] = PPG0_AND12_out[0];
assign PPG0_outs_vec[11] = PPG0_AND13_out[0];
assign PPG0_outs_vec[10] = PPG0_AND14_out[0];
assign PPG0_outs_vec[9] = PPG0_AND6_out[0];
assign PPG0_outs_vec[8] = PPG0_AND7_out[0];
assign PPG0_outs_vec[7] = PPG0_AND8_out[0];
assign PPG0_outs_vec[6] = PPG0_AND9_out[0];
assign PPG0_outs_vec[5] = PPG0_AND3_out[0];
assign PPG0_outs_vec[4] = PPG0_AND4_out[0];
assign PPG0_outs_vec[3] = PPG0_AND5_out[0];
assign PPG0_outs_vec[2] = PPG0_AND1_out[0];
assign PPG0_outs_vec[1] = PPG0_AND2_out[0];
assign PPG0_outs_vec[0] = PPG0_AND0_out[0];
assign ISCAS180_col_inputs_vec[2] = OutBits_ppg[3];
assign ISCAS180_col_inputs_vec[1] = OutBits_ppg[4];
assign ISCAS180_col_inputs_vec[0] = OutBits_ppg[5];
assign ISCAS180_outs_vec[44] = OutBits_ppg[143];
assign ISCAS180_outs_vec[43] = ISCAS180_FA9_cout[0];
assign ISCAS180_outs_vec[42] = ISCAS180_FA20_cout[0];
assign ISCAS180_outs_vec[41] = ISCAS180_FA9_sum[0];
assign ISCAS180_outs_vec[40] = ISCAS180_FA19_cout[0];
assign ISCAS180_outs_vec[39] = ISCAS180_FA20_sum[0];
assign ISCAS180_outs_vec[38] = ISCAS180_FA18_cout[0];
assign ISCAS180_outs_vec[37] = ISCAS180_FA19_sum[0];
assign ISCAS180_outs_vec[36] = ISCAS180_FA17_cout[0];
assign ISCAS180_outs_vec[35] = ISCAS180_FA18_sum[0];
assign ISCAS180_outs_vec[34] = ISCAS180_FA16_cout[0];
assign ISCAS180_outs_vec[33] = ISCAS180_FA17_sum[0];
assign ISCAS180_outs_vec[32] = ISCAS180_HA3_cout[0];
assign ISCAS180_outs_vec[31] = ISCAS180_FA16_sum[0];
assign ISCAS180_outs_vec[30] = ISCAS180_FA15_cout[0];
assign ISCAS180_outs_vec[29] = ISCAS180_HA3_sum[0];
assign ISCAS180_outs_vec[28] = ISCAS180_FA14_cout[0];
assign ISCAS180_outs_vec[27] = ISCAS180_FA15_sum[0];
assign ISCAS180_outs_vec[26] = ISCAS180_FA13_cout[0];
assign ISCAS180_outs_vec[25] = ISCAS180_FA14_sum[0];
assign ISCAS180_outs_vec[24] = ISCAS180_FA12_cout[0];
assign ISCAS180_outs_vec[23] = ISCAS180_FA13_sum[0];
assign ISCAS180_outs_vec[22] = ISCAS180_FA11_cout[0];
assign ISCAS180_outs_vec[21] = ISCAS180_FA12_sum[0];
assign ISCAS180_outs_vec[20] = ISCAS180_FA10_cout[0];
assign ISCAS180_outs_vec[19] = ISCAS180_FA11_sum[0];
assign ISCAS180_outs_vec[18] = ISCAS180_HA2_cout[0];
assign ISCAS180_outs_vec[17] = ISCAS180_FA10_sum[0];
assign ISCAS180_outs_vec[16] = ISCAS180_highorderAC18_OUTS[2];
assign ISCAS180_outs_vec[15] = ISCAS180_HA2_sum[0];
assign ISCAS180_outs_vec[14] = ISCAS180_highorderAC17_OUTS[1];
assign ISCAS180_outs_vec[13] = ISCAS180_highorderAC17_OUTS[0];
assign ISCAS180_outs_vec[12] = ISCAS180_highorderAC16_OUTS[1];
assign ISCAS180_outs_vec[11] = ISCAS180_highorderAC16_OUTS[0];
assign ISCAS180_outs_vec[10] = ISCAS180_highorderAC15_OUTS[1];
assign ISCAS180_outs_vec[9] = ISCAS180_highorderAC15_OUTS[0];
assign ISCAS180_outs_vec[8] = ISCAS180_highorderAC14_OUTS[1];
assign ISCAS180_outs_vec[7] = ISCAS180_highorderAC14_OUTS[0];
assign ISCAS180_outs_vec[6] = ISCAS180_highorderAC1_OUTS[1];
assign ISCAS180_outs_vec[5] = ISCAS180_highorderAC1_OUTS[0];
assign ISCAS180_outs_vec[4] = ISCAS180_highorderAC0_OUTS[1];
assign ISCAS180_outs_vec[3] = ISCAS180_highorderAC0_OUTS[0];
assign ISCAS180_outs_vec[2] = OutBits_ppg[2];
assign ISCAS180_outs_vec[1] = OutBits_ppg[1];
assign ISCAS180_outs_vec[0] = OutBits_ppg[0];
assign ISCAS180_highorderAC0_outs_vec[1] = ISCAS180_highorderAC0_AC320_out2[0];
assign ISCAS180_highorderAC0_outs_vec[0] = ISCAS180_highorderAC0_AC320_out1[0];
assign ISCAS180_slice_shadower1_INPUTS[3] = OutBits_ppg[6];
assign ISCAS180_slice_shadower1_INPUTS[2] = OutBits_ppg[7];
assign ISCAS180_slice_shadower1_INPUTS[1] = OutBits_ppg[8];
assign ISCAS180_slice_shadower1_INPUTS[0] = OutBits_ppg[9];
assign ISCAS180_highorderAC1_outs_vec[1] = ISCAS180_highorderAC1_AC420_out2[0];
assign ISCAS180_highorderAC1_outs_vec[0] = ISCAS180_highorderAC1_AC420_out1[0];
assign ISCAS180_slice_shadower2_INPUTS[4] = OutBits_ppg[10];
assign ISCAS180_slice_shadower2_INPUTS[3] = OutBits_ppg[11];
assign ISCAS180_slice_shadower2_INPUTS[2] = OutBits_ppg[12];
assign ISCAS180_slice_shadower2_INPUTS[1] = OutBits_ppg[13];
assign ISCAS180_slice_shadower2_INPUTS[0] = OutBits_ppg[14];
assign ISCAS180_highorderAC2_outs_vec[2] = ISCAS180_highorderAC2_AC530_out3[0];
assign ISCAS180_highorderAC2_outs_vec[1] = ISCAS180_highorderAC2_AC530_out2[0];
assign ISCAS180_highorderAC2_outs_vec[0] = ISCAS180_highorderAC2_AC530_out1[0];
assign ISCAS180_slice_shadower3_INPUTS[5] = OutBits_ppg[15];
assign ISCAS180_slice_shadower3_INPUTS[4] = OutBits_ppg[16];
assign ISCAS180_slice_shadower3_INPUTS[3] = OutBits_ppg[17];
assign ISCAS180_slice_shadower3_INPUTS[2] = OutBits_ppg[18];
assign ISCAS180_slice_shadower3_INPUTS[1] = OutBits_ppg[19];
assign ISCAS180_slice_shadower3_INPUTS[0] = OutBits_ppg[20];
assign ISCAS180_highorderAC3_outs_vec[2] = ISCAS180_highorderAC3_AC630_out3[0];
assign ISCAS180_highorderAC3_outs_vec[1] = ISCAS180_highorderAC3_AC630_out2[0];
assign ISCAS180_highorderAC3_outs_vec[0] = ISCAS180_highorderAC3_AC630_out1[0];
assign ISCAS180_slice_shadower4_INPUTS[6] = OutBits_ppg[21];
assign ISCAS180_slice_shadower4_INPUTS[5] = OutBits_ppg[22];
assign ISCAS180_slice_shadower4_INPUTS[4] = OutBits_ppg[23];
assign ISCAS180_slice_shadower4_INPUTS[3] = OutBits_ppg[24];
assign ISCAS180_slice_shadower4_INPUTS[2] = OutBits_ppg[25];
assign ISCAS180_slice_shadower4_INPUTS[1] = OutBits_ppg[26];
assign ISCAS180_slice_shadower4_INPUTS[0] = OutBits_ppg[27];
assign ISCAS180_highorderAC4_outs_vec[3] = ISCAS180_highorderAC4_AC421_out2[0];
assign ISCAS180_highorderAC4_outs_vec[2] = ISCAS180_highorderAC4_AC421_out1[0];
assign ISCAS180_highorderAC4_outs_vec[1] = ISCAS180_highorderAC4_AC321_out2[0];
assign ISCAS180_highorderAC4_outs_vec[0] = ISCAS180_highorderAC4_AC321_out1[0];
assign ISCAS180_slice_shadower5_INPUTS[7] = OutBits_ppg[28];
assign ISCAS180_slice_shadower5_INPUTS[6] = OutBits_ppg[29];
assign ISCAS180_slice_shadower5_INPUTS[5] = OutBits_ppg[30];
assign ISCAS180_slice_shadower5_INPUTS[4] = OutBits_ppg[31];
assign ISCAS180_slice_shadower5_INPUTS[3] = OutBits_ppg[32];
assign ISCAS180_slice_shadower5_INPUTS[2] = OutBits_ppg[33];
assign ISCAS180_slice_shadower5_INPUTS[1] = OutBits_ppg[34];
assign ISCAS180_slice_shadower5_INPUTS[0] = OutBits_ppg[35];
assign ISCAS180_highorderAC5_outs_vec[3] = ISCAS180_highorderAC5_AC423_out2[0];
assign ISCAS180_highorderAC5_outs_vec[2] = ISCAS180_highorderAC5_AC423_out1[0];
assign ISCAS180_highorderAC5_outs_vec[1] = ISCAS180_highorderAC5_AC422_out2[0];
assign ISCAS180_highorderAC5_outs_vec[0] = ISCAS180_highorderAC5_AC422_out1[0];
assign ISCAS180_slice_shadower6_INPUTS[8] = OutBits_ppg[36];
assign ISCAS180_slice_shadower6_INPUTS[7] = OutBits_ppg[37];
assign ISCAS180_slice_shadower6_INPUTS[6] = OutBits_ppg[38];
assign ISCAS180_slice_shadower6_INPUTS[5] = OutBits_ppg[39];
assign ISCAS180_slice_shadower6_INPUTS[4] = OutBits_ppg[40];
assign ISCAS180_slice_shadower6_INPUTS[3] = OutBits_ppg[41];
assign ISCAS180_slice_shadower6_INPUTS[2] = OutBits_ppg[42];
assign ISCAS180_slice_shadower6_INPUTS[1] = OutBits_ppg[43];
assign ISCAS180_slice_shadower6_INPUTS[0] = OutBits_ppg[44];
assign ISCAS180_highorderAC6_outs_vec[4] = ISCAS180_highorderAC6_AC531_out3[0];
assign ISCAS180_highorderAC6_outs_vec[3] = ISCAS180_highorderAC6_AC531_out2[0];
assign ISCAS180_highorderAC6_outs_vec[2] = ISCAS180_highorderAC6_AC531_out1[0];
assign ISCAS180_highorderAC6_outs_vec[1] = ISCAS180_highorderAC6_AC424_out2[0];
assign ISCAS180_highorderAC6_outs_vec[0] = ISCAS180_highorderAC6_AC424_out1[0];
assign ISCAS180_slice_shadower7_INPUTS[9] = OutBits_ppg[45];
assign ISCAS180_slice_shadower7_INPUTS[8] = OutBits_ppg[46];
assign ISCAS180_slice_shadower7_INPUTS[7] = OutBits_ppg[47];
assign ISCAS180_slice_shadower7_INPUTS[6] = OutBits_ppg[48];
assign ISCAS180_slice_shadower7_INPUTS[5] = OutBits_ppg[49];
assign ISCAS180_slice_shadower7_INPUTS[4] = OutBits_ppg[50];
assign ISCAS180_slice_shadower7_INPUTS[3] = OutBits_ppg[51];
assign ISCAS180_slice_shadower7_INPUTS[2] = OutBits_ppg[52];
assign ISCAS180_slice_shadower7_INPUTS[1] = OutBits_ppg[53];
assign ISCAS180_slice_shadower7_INPUTS[0] = OutBits_ppg[54];
assign ISCAS180_highorderAC7_outs_vec[4] = ISCAS180_highorderAC7_AC631_out3[0];
assign ISCAS180_highorderAC7_outs_vec[3] = ISCAS180_highorderAC7_AC631_out2[0];
assign ISCAS180_highorderAC7_outs_vec[2] = ISCAS180_highorderAC7_AC631_out1[0];
assign ISCAS180_highorderAC7_outs_vec[1] = ISCAS180_highorderAC7_AC425_out2[0];
assign ISCAS180_highorderAC7_outs_vec[0] = ISCAS180_highorderAC7_AC425_out1[0];
assign ISCAS180_slice_shadower8_INPUTS[10] = OutBits_ppg[55];
assign ISCAS180_slice_shadower8_INPUTS[9] = OutBits_ppg[56];
assign ISCAS180_slice_shadower8_INPUTS[8] = OutBits_ppg[57];
assign ISCAS180_slice_shadower8_INPUTS[7] = OutBits_ppg[58];
assign ISCAS180_slice_shadower8_INPUTS[6] = OutBits_ppg[59];
assign ISCAS180_slice_shadower8_INPUTS[5] = OutBits_ppg[60];
assign ISCAS180_slice_shadower8_INPUTS[4] = OutBits_ppg[61];
assign ISCAS180_slice_shadower8_INPUTS[3] = OutBits_ppg[62];
assign ISCAS180_slice_shadower8_INPUTS[2] = OutBits_ppg[63];
assign ISCAS180_slice_shadower8_INPUTS[1] = OutBits_ppg[64];
assign ISCAS180_slice_shadower8_INPUTS[0] = OutBits_ppg[65];
assign ISCAS180_highorderAC8_outs_vec[5] = ISCAS180_highorderAC8_AC427_out2[0];
assign ISCAS180_highorderAC8_outs_vec[4] = ISCAS180_highorderAC8_AC427_out1[0];
assign ISCAS180_highorderAC8_outs_vec[3] = ISCAS180_highorderAC8_AC426_out2[0];
assign ISCAS180_highorderAC8_outs_vec[2] = ISCAS180_highorderAC8_AC426_out1[0];
assign ISCAS180_highorderAC8_outs_vec[1] = ISCAS180_highorderAC8_AC322_out2[0];
assign ISCAS180_highorderAC8_outs_vec[0] = ISCAS180_highorderAC8_AC322_out1[0];
assign ISCAS180_slice_shadower9_INPUTS[11] = OutBits_ppg[66];
assign ISCAS180_slice_shadower9_INPUTS[10] = OutBits_ppg[67];
assign ISCAS180_slice_shadower9_INPUTS[9] = OutBits_ppg[68];
assign ISCAS180_slice_shadower9_INPUTS[8] = OutBits_ppg[69];
assign ISCAS180_slice_shadower9_INPUTS[7] = OutBits_ppg[70];
assign ISCAS180_slice_shadower9_INPUTS[6] = OutBits_ppg[71];
assign ISCAS180_slice_shadower9_INPUTS[5] = OutBits_ppg[72];
assign ISCAS180_slice_shadower9_INPUTS[4] = OutBits_ppg[73];
assign ISCAS180_slice_shadower9_INPUTS[3] = OutBits_ppg[74];
assign ISCAS180_slice_shadower9_INPUTS[2] = OutBits_ppg[75];
assign ISCAS180_slice_shadower9_INPUTS[1] = OutBits_ppg[76];
assign ISCAS180_slice_shadower9_INPUTS[0] = OutBits_ppg[77];
assign ISCAS180_highorderAC9_outs_vec[5] = ISCAS180_highorderAC9_AC4210_out2[0];
assign ISCAS180_highorderAC9_outs_vec[4] = ISCAS180_highorderAC9_AC4210_out1[0];
assign ISCAS180_highorderAC9_outs_vec[3] = ISCAS180_highorderAC9_AC429_out2[0];
assign ISCAS180_highorderAC9_outs_vec[2] = ISCAS180_highorderAC9_AC429_out1[0];
assign ISCAS180_highorderAC9_outs_vec[1] = ISCAS180_highorderAC9_AC428_out2[0];
assign ISCAS180_highorderAC9_outs_vec[0] = ISCAS180_highorderAC9_AC428_out1[0];
assign ISCAS180_slice_shadower10_INPUTS[10] = OutBits_ppg[78];
assign ISCAS180_slice_shadower10_INPUTS[9] = OutBits_ppg[79];
assign ISCAS180_slice_shadower10_INPUTS[8] = OutBits_ppg[80];
assign ISCAS180_slice_shadower10_INPUTS[7] = OutBits_ppg[81];
assign ISCAS180_slice_shadower10_INPUTS[6] = OutBits_ppg[82];
assign ISCAS180_slice_shadower10_INPUTS[5] = OutBits_ppg[83];
assign ISCAS180_slice_shadower10_INPUTS[4] = OutBits_ppg[84];
assign ISCAS180_slice_shadower10_INPUTS[3] = OutBits_ppg[85];
assign ISCAS180_slice_shadower10_INPUTS[2] = OutBits_ppg[86];
assign ISCAS180_slice_shadower10_INPUTS[1] = OutBits_ppg[87];
assign ISCAS180_slice_shadower10_INPUTS[0] = OutBits_ppg[88];
assign ISCAS180_highorderAC10_outs_vec[5] = ISCAS180_highorderAC10_AC4212_out2[0];
assign ISCAS180_highorderAC10_outs_vec[4] = ISCAS180_highorderAC10_AC4212_out1[0];
assign ISCAS180_highorderAC10_outs_vec[3] = ISCAS180_highorderAC10_AC4211_out2[0];
assign ISCAS180_highorderAC10_outs_vec[2] = ISCAS180_highorderAC10_AC4211_out1[0];
assign ISCAS180_highorderAC10_outs_vec[1] = ISCAS180_highorderAC10_AC323_out2[0];
assign ISCAS180_highorderAC10_outs_vec[0] = ISCAS180_highorderAC10_AC323_out1[0];
assign ISCAS180_slice_shadower11_INPUTS[9] = OutBits_ppg[89];
assign ISCAS180_slice_shadower11_INPUTS[8] = OutBits_ppg[90];
assign ISCAS180_slice_shadower11_INPUTS[7] = OutBits_ppg[91];
assign ISCAS180_slice_shadower11_INPUTS[6] = OutBits_ppg[92];
assign ISCAS180_slice_shadower11_INPUTS[5] = OutBits_ppg[93];
assign ISCAS180_slice_shadower11_INPUTS[4] = OutBits_ppg[94];
assign ISCAS180_slice_shadower11_INPUTS[3] = OutBits_ppg[95];
assign ISCAS180_slice_shadower11_INPUTS[2] = OutBits_ppg[96];
assign ISCAS180_slice_shadower11_INPUTS[1] = OutBits_ppg[97];
assign ISCAS180_slice_shadower11_INPUTS[0] = OutBits_ppg[98];
assign ISCAS180_highorderAC11_outs_vec[4] = ISCAS180_highorderAC11_AC632_out3[0];
assign ISCAS180_highorderAC11_outs_vec[3] = ISCAS180_highorderAC11_AC632_out2[0];
assign ISCAS180_highorderAC11_outs_vec[2] = ISCAS180_highorderAC11_AC632_out1[0];
assign ISCAS180_highorderAC11_outs_vec[1] = ISCAS180_highorderAC11_AC4213_out2[0];
assign ISCAS180_highorderAC11_outs_vec[0] = ISCAS180_highorderAC11_AC4213_out1[0];
assign ISCAS180_slice_shadower12_INPUTS[8] = OutBits_ppg[99];
assign ISCAS180_slice_shadower12_INPUTS[7] = OutBits_ppg[100];
assign ISCAS180_slice_shadower12_INPUTS[6] = OutBits_ppg[101];
assign ISCAS180_slice_shadower12_INPUTS[5] = OutBits_ppg[102];
assign ISCAS180_slice_shadower12_INPUTS[4] = OutBits_ppg[103];
assign ISCAS180_slice_shadower12_INPUTS[3] = OutBits_ppg[104];
assign ISCAS180_slice_shadower12_INPUTS[2] = OutBits_ppg[105];
assign ISCAS180_slice_shadower12_INPUTS[1] = OutBits_ppg[106];
assign ISCAS180_slice_shadower12_INPUTS[0] = OutBits_ppg[107];
assign ISCAS180_highorderAC12_outs_vec[4] = ISCAS180_highorderAC12_AC532_out3[0];
assign ISCAS180_highorderAC12_outs_vec[3] = ISCAS180_highorderAC12_AC532_out2[0];
assign ISCAS180_highorderAC12_outs_vec[2] = ISCAS180_highorderAC12_AC532_out1[0];
assign ISCAS180_highorderAC12_outs_vec[1] = ISCAS180_highorderAC12_AC4214_out2[0];
assign ISCAS180_highorderAC12_outs_vec[0] = ISCAS180_highorderAC12_AC4214_out1[0];
assign ISCAS180_slice_shadower13_INPUTS[7] = OutBits_ppg[108];
assign ISCAS180_slice_shadower13_INPUTS[6] = OutBits_ppg[109];
assign ISCAS180_slice_shadower13_INPUTS[5] = OutBits_ppg[110];
assign ISCAS180_slice_shadower13_INPUTS[4] = OutBits_ppg[111];
assign ISCAS180_slice_shadower13_INPUTS[3] = OutBits_ppg[112];
assign ISCAS180_slice_shadower13_INPUTS[2] = OutBits_ppg[113];
assign ISCAS180_slice_shadower13_INPUTS[1] = OutBits_ppg[114];
assign ISCAS180_slice_shadower13_INPUTS[0] = OutBits_ppg[115];
assign ISCAS180_highorderAC13_outs_vec[3] = ISCAS180_highorderAC13_AC4216_out2[0];
assign ISCAS180_highorderAC13_outs_vec[2] = ISCAS180_highorderAC13_AC4216_out1[0];
assign ISCAS180_highorderAC13_outs_vec[1] = ISCAS180_highorderAC13_AC4215_out2[0];
assign ISCAS180_highorderAC13_outs_vec[0] = ISCAS180_highorderAC13_AC4215_out1[0];
assign ISCAS180_slice_shadower14_INPUTS[2] = ISCAS180_highorderAC2_OUTS[2];
assign ISCAS180_slice_shadower14_INPUTS[1] = ISCAS180_highorderAC2_OUTS[1];
assign ISCAS180_slice_shadower14_INPUTS[0] = ISCAS180_highorderAC2_OUTS[0];
assign ISCAS180_highorderAC14_outs_vec[1] = ISCAS180_highorderAC14_AC324_out2[0];
assign ISCAS180_highorderAC14_outs_vec[0] = ISCAS180_highorderAC14_AC324_out1[0];
assign ISCAS180_slice_shadower15_INPUTS[2] = ISCAS180_highorderAC3_OUTS[2];
assign ISCAS180_slice_shadower15_INPUTS[1] = ISCAS180_highorderAC3_OUTS[1];
assign ISCAS180_slice_shadower15_INPUTS[0] = ISCAS180_highorderAC3_OUTS[0];
assign ISCAS180_highorderAC15_outs_vec[1] = ISCAS180_highorderAC15_AC325_out2[0];
assign ISCAS180_highorderAC15_outs_vec[0] = ISCAS180_highorderAC15_AC325_out1[0];
assign ISCAS180_slice_shadower16_INPUTS[3] = ISCAS180_highorderAC4_OUTS[3];
assign ISCAS180_slice_shadower16_INPUTS[2] = ISCAS180_highorderAC4_OUTS[2];
assign ISCAS180_slice_shadower16_INPUTS[1] = ISCAS180_highorderAC4_OUTS[1];
assign ISCAS180_slice_shadower16_INPUTS[0] = ISCAS180_highorderAC4_OUTS[0];
assign ISCAS180_highorderAC16_outs_vec[1] = ISCAS180_highorderAC16_AC4217_out2[0];
assign ISCAS180_highorderAC16_outs_vec[0] = ISCAS180_highorderAC16_AC4217_out1[0];
assign ISCAS180_slice_shadower17_INPUTS[3] = ISCAS180_highorderAC5_OUTS[3];
assign ISCAS180_slice_shadower17_INPUTS[2] = ISCAS180_highorderAC5_OUTS[2];
assign ISCAS180_slice_shadower17_INPUTS[1] = ISCAS180_highorderAC5_OUTS[1];
assign ISCAS180_slice_shadower17_INPUTS[0] = ISCAS180_highorderAC5_OUTS[0];
assign ISCAS180_highorderAC17_outs_vec[1] = ISCAS180_highorderAC17_AC4218_out2[0];
assign ISCAS180_highorderAC17_outs_vec[0] = ISCAS180_highorderAC17_AC4218_out1[0];
assign ISCAS180_slice_shadower18_INPUTS[4] = ISCAS180_highorderAC6_OUTS[4];
assign ISCAS180_slice_shadower18_INPUTS[3] = ISCAS180_highorderAC6_OUTS[3];
assign ISCAS180_slice_shadower18_INPUTS[2] = ISCAS180_highorderAC6_OUTS[2];
assign ISCAS180_slice_shadower18_INPUTS[1] = ISCAS180_highorderAC6_OUTS[1];
assign ISCAS180_slice_shadower18_INPUTS[0] = ISCAS180_highorderAC6_OUTS[0];
assign ISCAS180_highorderAC18_outs_vec[2] = ISCAS180_highorderAC18_AC533_out3[0];
assign ISCAS180_highorderAC18_outs_vec[1] = ISCAS180_highorderAC18_AC533_out2[0];
assign ISCAS180_highorderAC18_outs_vec[0] = ISCAS180_highorderAC18_AC533_out1[0];
assign ISCAS180_slice_shadower19_INPUTS[4] = ISCAS180_highorderAC7_OUTS[4];
assign ISCAS180_slice_shadower19_INPUTS[3] = ISCAS180_highorderAC7_OUTS[3];
assign ISCAS180_slice_shadower19_INPUTS[2] = ISCAS180_highorderAC7_OUTS[2];
assign ISCAS180_slice_shadower19_INPUTS[1] = ISCAS180_highorderAC7_OUTS[1];
assign ISCAS180_slice_shadower19_INPUTS[0] = ISCAS180_highorderAC7_OUTS[0];
assign ISCAS180_highorderAC19_outs_vec[2] = ISCAS180_highorderAC19_AC534_out3[0];
assign ISCAS180_highorderAC19_outs_vec[1] = ISCAS180_highorderAC19_AC534_out2[0];
assign ISCAS180_highorderAC19_outs_vec[0] = ISCAS180_highorderAC19_AC534_out1[0];
assign ISCAS180_slice_shadower20_INPUTS[5] = ISCAS180_highorderAC8_OUTS[5];
assign ISCAS180_slice_shadower20_INPUTS[4] = ISCAS180_highorderAC8_OUTS[4];
assign ISCAS180_slice_shadower20_INPUTS[3] = ISCAS180_highorderAC8_OUTS[3];
assign ISCAS180_slice_shadower20_INPUTS[2] = ISCAS180_highorderAC8_OUTS[2];
assign ISCAS180_slice_shadower20_INPUTS[1] = ISCAS180_highorderAC8_OUTS[1];
assign ISCAS180_slice_shadower20_INPUTS[0] = ISCAS180_highorderAC8_OUTS[0];
assign ISCAS180_highorderAC20_outs_vec[2] = ISCAS180_highorderAC20_AC633_out3[0];
assign ISCAS180_highorderAC20_outs_vec[1] = ISCAS180_highorderAC20_AC633_out2[0];
assign ISCAS180_highorderAC20_outs_vec[0] = ISCAS180_highorderAC20_AC633_out1[0];
assign ISCAS180_slice_shadower21_INPUTS[5] = ISCAS180_highorderAC9_OUTS[5];
assign ISCAS180_slice_shadower21_INPUTS[4] = ISCAS180_highorderAC9_OUTS[4];
assign ISCAS180_slice_shadower21_INPUTS[3] = ISCAS180_highorderAC9_OUTS[3];
assign ISCAS180_slice_shadower21_INPUTS[2] = ISCAS180_highorderAC9_OUTS[2];
assign ISCAS180_slice_shadower21_INPUTS[1] = ISCAS180_highorderAC9_OUTS[1];
assign ISCAS180_slice_shadower21_INPUTS[0] = ISCAS180_highorderAC9_OUTS[0];
assign ISCAS180_highorderAC21_outs_vec[2] = ISCAS180_highorderAC21_AC634_out3[0];
assign ISCAS180_highorderAC21_outs_vec[1] = ISCAS180_highorderAC21_AC634_out2[0];
assign ISCAS180_highorderAC21_outs_vec[0] = ISCAS180_highorderAC21_AC634_out1[0];
assign ISCAS180_slice_shadower22_INPUTS[5] = ISCAS180_highorderAC10_OUTS[5];
assign ISCAS180_slice_shadower22_INPUTS[4] = ISCAS180_highorderAC10_OUTS[4];
assign ISCAS180_slice_shadower22_INPUTS[3] = ISCAS180_highorderAC10_OUTS[3];
assign ISCAS180_slice_shadower22_INPUTS[2] = ISCAS180_highorderAC10_OUTS[2];
assign ISCAS180_slice_shadower22_INPUTS[1] = ISCAS180_highorderAC10_OUTS[1];
assign ISCAS180_slice_shadower22_INPUTS[0] = ISCAS180_highorderAC10_OUTS[0];
assign ISCAS180_highorderAC22_outs_vec[2] = ISCAS180_highorderAC22_AC635_out3[0];
assign ISCAS180_highorderAC22_outs_vec[1] = ISCAS180_highorderAC22_AC635_out2[0];
assign ISCAS180_highorderAC22_outs_vec[0] = ISCAS180_highorderAC22_AC635_out1[0];
assign ISCAS180_slice_shadower23_INPUTS[4] = ISCAS180_highorderAC11_OUTS[4];
assign ISCAS180_slice_shadower23_INPUTS[3] = ISCAS180_highorderAC11_OUTS[3];
assign ISCAS180_slice_shadower23_INPUTS[2] = ISCAS180_highorderAC11_OUTS[2];
assign ISCAS180_slice_shadower23_INPUTS[1] = ISCAS180_highorderAC11_OUTS[1];
assign ISCAS180_slice_shadower23_INPUTS[0] = ISCAS180_highorderAC11_OUTS[0];
assign ISCAS180_highorderAC23_outs_vec[2] = ISCAS180_highorderAC23_AC535_out3[0];
assign ISCAS180_highorderAC23_outs_vec[1] = ISCAS180_highorderAC23_AC535_out2[0];
assign ISCAS180_highorderAC23_outs_vec[0] = ISCAS180_highorderAC23_AC535_out1[0];
assign ISCAS180_slice_shadower24_INPUTS[4] = ISCAS180_highorderAC12_OUTS[4];
assign ISCAS180_slice_shadower24_INPUTS[3] = ISCAS180_highorderAC12_OUTS[3];
assign ISCAS180_slice_shadower24_INPUTS[2] = ISCAS180_highorderAC12_OUTS[2];
assign ISCAS180_slice_shadower24_INPUTS[1] = ISCAS180_highorderAC12_OUTS[1];
assign ISCAS180_slice_shadower24_INPUTS[0] = ISCAS180_highorderAC12_OUTS[0];
assign ISCAS180_highorderAC24_outs_vec[2] = ISCAS180_highorderAC24_AC536_out3[0];
assign ISCAS180_highorderAC24_outs_vec[1] = ISCAS180_highorderAC24_AC536_out2[0];
assign ISCAS180_highorderAC24_outs_vec[0] = ISCAS180_highorderAC24_AC536_out1[0];
assign ISCAS180_slice_shadower25_INPUTS[3] = ISCAS180_highorderAC13_OUTS[3];
assign ISCAS180_slice_shadower25_INPUTS[2] = ISCAS180_highorderAC13_OUTS[2];
assign ISCAS180_slice_shadower25_INPUTS[1] = ISCAS180_highorderAC13_OUTS[1];
assign ISCAS180_slice_shadower25_INPUTS[0] = ISCAS180_highorderAC13_OUTS[0];
assign ISCAS180_highorderAC25_outs_vec[1] = ISCAS180_highorderAC25_AC4219_out2[0];
assign ISCAS180_highorderAC25_outs_vec[0] = ISCAS180_highorderAC25_AC4219_out1[0];



assign PPG0_AND0_out = (A[0] & B[0]);



assign PPG0_AND1_out = (A[1] & B[0]);



assign PPG0_AND2_out = (A[0] & B[1]);



assign PPG0_AND3_out = (A[2] & B[0]);



assign PPG0_AND4_out = (A[1] & B[1]);



assign PPG0_AND5_out = (A[0] & B[2]);



assign PPG0_AND6_out = (A[3] & B[0]);



assign PPG0_AND7_out = (A[2] & B[1]);



assign PPG0_AND8_out = (A[1] & B[2]);



assign PPG0_AND9_out = (A[0] & B[3]);



assign PPG0_AND10_out = (A[4] & B[0]);



assign PPG0_AND11_out = (A[3] & B[1]);



assign PPG0_AND12_out = (A[2] & B[2]);



assign PPG0_AND13_out = (A[1] & B[3]);



assign PPG0_AND14_out = (A[0] & B[4]);



assign PPG0_AND15_out = (A[5] & B[0]);



assign PPG0_AND16_out = (A[4] & B[1]);



assign PPG0_AND17_out = (A[3] & B[2]);



assign PPG0_AND18_out = (A[2] & B[3]);



assign PPG0_AND19_out = (A[1] & B[4]);



assign PPG0_AND20_out = (A[0] & B[5]);



assign PPG0_AND21_out = (A[6] & B[0]);



assign PPG0_AND22_out = (A[5] & B[1]);



assign PPG0_AND23_out = (A[4] & B[2]);



assign PPG0_AND24_out = (A[3] & B[3]);



assign PPG0_AND25_out = (A[2] & B[4]);



assign PPG0_AND26_out = (A[1] & B[5]);



assign PPG0_AND27_out = (A[0] & B[6]);



assign PPG0_AND28_out = (A[7] & B[0]);



assign PPG0_AND29_out = (A[6] & B[1]);



assign PPG0_AND30_out = (A[5] & B[2]);



assign PPG0_AND31_out = (A[4] & B[3]);



assign PPG0_AND32_out = (A[3] & B[4]);



assign PPG0_AND33_out = (A[2] & B[5]);



assign PPG0_AND34_out = (A[1] & B[6]);



assign PPG0_AND35_out = (A[0] & B[7]);



assign PPG0_AND36_out = (A[8] & B[0]);



assign PPG0_AND37_out = (A[7] & B[1]);



assign PPG0_AND38_out = (A[6] & B[2]);



assign PPG0_AND39_out = (A[5] & B[3]);



assign PPG0_AND40_out = (A[4] & B[4]);



assign PPG0_AND41_out = (A[3] & B[5]);



assign PPG0_AND42_out = (A[2] & B[6]);



assign PPG0_AND43_out = (A[1] & B[7]);



assign PPG0_AND44_out = (A[0] & B[8]);



assign PPG0_AND45_out = (A[9] & B[0]);



assign PPG0_AND46_out = (A[8] & B[1]);



assign PPG0_AND47_out = (A[7] & B[2]);



assign PPG0_AND48_out = (A[6] & B[3]);



assign PPG0_AND49_out = (A[5] & B[4]);



assign PPG0_AND50_out = (A[4] & B[5]);



assign PPG0_AND51_out = (A[3] & B[6]);



assign PPG0_AND52_out = (A[2] & B[7]);



assign PPG0_AND53_out = (A[1] & B[8]);



assign PPG0_AND54_out = (A[0] & B[9]);



assign PPG0_AND55_out = (A[10] & B[0]);



assign PPG0_AND56_out = (A[9] & B[1]);



assign PPG0_AND57_out = (A[8] & B[2]);



assign PPG0_AND58_out = (A[7] & B[3]);



assign PPG0_AND59_out = (A[6] & B[4]);



assign PPG0_AND60_out = (A[5] & B[5]);



assign PPG0_AND61_out = (A[4] & B[6]);



assign PPG0_AND62_out = (A[3] & B[7]);



assign PPG0_AND63_out = (A[2] & B[8]);



assign PPG0_AND64_out = (A[1] & B[9]);



assign PPG0_AND65_out = (A[0] & B[10]);



assign PPG0_AND66_out = (A[11] & B[0]);



assign PPG0_AND67_out = (A[10] & B[1]);



assign PPG0_AND68_out = (A[9] & B[2]);



assign PPG0_AND69_out = (A[8] & B[3]);



assign PPG0_AND70_out = (A[7] & B[4]);



assign PPG0_AND71_out = (A[6] & B[5]);



assign PPG0_AND72_out = (A[5] & B[6]);



assign PPG0_AND73_out = (A[4] & B[7]);



assign PPG0_AND74_out = (A[3] & B[8]);



assign PPG0_AND75_out = (A[2] & B[9]);



assign PPG0_AND76_out = (A[1] & B[10]);



assign PPG0_AND77_out = (A[0] & B[11]);



assign PPG0_AND78_out = (A[11] & B[1]);



assign PPG0_AND79_out = (A[10] & B[2]);



assign PPG0_AND80_out = (A[9] & B[3]);



assign PPG0_AND81_out = (A[8] & B[4]);



assign PPG0_AND82_out = (A[7] & B[5]);



assign PPG0_AND83_out = (A[6] & B[6]);



assign PPG0_AND84_out = (A[5] & B[7]);



assign PPG0_AND85_out = (A[4] & B[8]);



assign PPG0_AND86_out = (A[3] & B[9]);



assign PPG0_AND87_out = (A[2] & B[10]);



assign PPG0_AND88_out = (A[1] & B[11]);



assign PPG0_AND89_out = (A[11] & B[2]);



assign PPG0_AND90_out = (A[10] & B[3]);



assign PPG0_AND91_out = (A[9] & B[4]);



assign PPG0_AND92_out = (A[8] & B[5]);



assign PPG0_AND93_out = (A[7] & B[6]);



assign PPG0_AND94_out = (A[6] & B[7]);



assign PPG0_AND95_out = (A[5] & B[8]);



assign PPG0_AND96_out = (A[4] & B[9]);



assign PPG0_AND97_out = (A[3] & B[10]);



assign PPG0_AND98_out = (A[2] & B[11]);



assign PPG0_AND99_out = (A[11] & B[3]);



assign PPG0_AND100_out = (A[10] & B[4]);



assign PPG0_AND101_out = (A[9] & B[5]);



assign PPG0_AND102_out = (A[8] & B[6]);



assign PPG0_AND103_out = (A[7] & B[7]);



assign PPG0_AND104_out = (A[6] & B[8]);



assign PPG0_AND105_out = (A[5] & B[9]);



assign PPG0_AND106_out = (A[4] & B[10]);



assign PPG0_AND107_out = (A[3] & B[11]);



assign PPG0_AND108_out = (A[11] & B[4]);



assign PPG0_AND109_out = (A[10] & B[5]);



assign PPG0_AND110_out = (A[9] & B[6]);



assign PPG0_AND111_out = (A[8] & B[7]);



assign PPG0_AND112_out = (A[7] & B[8]);



assign PPG0_AND113_out = (A[6] & B[9]);



assign PPG0_AND114_out = (A[5] & B[10]);



assign PPG0_AND115_out = (A[4] & B[11]);



assign PPG0_AND116_out = (A[11] & B[5]);



assign PPG0_AND117_out = (A[10] & B[6]);



assign PPG0_AND118_out = (A[9] & B[7]);



assign PPG0_AND119_out = (A[8] & B[8]);



assign PPG0_AND120_out = (A[7] & B[9]);



assign PPG0_AND121_out = (A[6] & B[10]);



assign PPG0_AND122_out = (A[5] & B[11]);



assign PPG0_AND123_out = (A[11] & B[6]);



assign PPG0_AND124_out = (A[10] & B[7]);



assign PPG0_AND125_out = (A[9] & B[8]);



assign PPG0_AND126_out = (A[8] & B[9]);



assign PPG0_AND127_out = (A[7] & B[10]);



assign PPG0_AND128_out = (A[6] & B[11]);



assign PPG0_AND129_out = (A[11] & B[7]);



assign PPG0_AND130_out = (A[10] & B[8]);



assign PPG0_AND131_out = (A[9] & B[9]);



assign PPG0_AND132_out = (A[8] & B[10]);



assign PPG0_AND133_out = (A[7] & B[11]);



assign PPG0_AND134_out = (A[11] & B[8]);



assign PPG0_AND135_out = (A[10] & B[9]);



assign PPG0_AND136_out = (A[9] & B[10]);



assign PPG0_AND137_out = (A[8] & B[11]);



assign PPG0_AND138_out = (A[11] & B[9]);



assign PPG0_AND139_out = (A[10] & B[10]);



assign PPG0_AND140_out = (A[9] & B[11]);



assign PPG0_AND141_out = (A[11] & B[10]);



assign PPG0_AND142_out = (A[10] & B[11]);



assign PPG0_AND143_out = (A[11] & B[11]);



assign OutBits_ppg = PPG0_outs_vec;



assign ISCAS180_vInputs = ISCAS180_col_inputs_vec;



assign ISCAS180_highorderAC0_AC320_out2 = ((ISCAS180_vInputs[0] & ISCAS180_vInputs[1]) | ISCAS180_vInputs[2]);
assign ISCAS180_highorderAC0_AC320_out1 = (ISCAS180_vInputs[0] | ISCAS180_vInputs[1]);



assign ISCAS180_highorderAC0_OUTS = ISCAS180_highorderAC0_outs_vec;



assign ISCAS180_slice_shadower1_OUTS = ISCAS180_slice_shadower1_INPUTS;



assign ISCAS180_highorderAC1_AC420_out2 = (((ISCAS180_slice_shadower1_OUTS[0] & ISCAS180_slice_shadower1_OUTS[1]) | ISCAS180_slice_shadower1_OUTS[2]) | ISCAS180_slice_shadower1_OUTS[3]);
assign ISCAS180_highorderAC1_AC420_out1 = (((ISCAS180_slice_shadower1_OUTS[2] & ISCAS180_slice_shadower1_OUTS[3]) | ISCAS180_slice_shadower1_OUTS[0]) | ISCAS180_slice_shadower1_OUTS[1]);



assign ISCAS180_highorderAC1_OUTS = ISCAS180_highorderAC1_outs_vec;



assign ISCAS180_slice_shadower2_OUTS = ISCAS180_slice_shadower2_INPUTS;



assign ISCAS180_highorderAC2_AC530_out3 = (((ISCAS180_slice_shadower2_OUTS[0] & ISCAS180_slice_shadower2_OUTS[1]) | ISCAS180_slice_shadower2_OUTS[2]) | ISCAS180_slice_shadower2_OUTS[3]);
assign ISCAS180_highorderAC2_AC530_out2 = (ISCAS180_slice_shadower2_OUTS[0] | ISCAS180_slice_shadower2_OUTS[1]);
assign ISCAS180_highorderAC2_AC530_out1 = ((ISCAS180_slice_shadower2_OUTS[2] & ISCAS180_slice_shadower2_OUTS[3]) | ISCAS180_slice_shadower2_OUTS[4]);



assign ISCAS180_highorderAC2_OUTS = ISCAS180_highorderAC2_outs_vec;



assign ISCAS180_slice_shadower3_OUTS = ISCAS180_slice_shadower3_INPUTS;



assign ISCAS180_highorderAC3_AC630_out3 = (((ISCAS180_slice_shadower3_OUTS[0] & ISCAS180_slice_shadower3_OUTS[1]) | ISCAS180_slice_shadower3_OUTS[2]) | ISCAS180_slice_shadower3_OUTS[3]);
assign ISCAS180_highorderAC3_AC630_out2 = (((ISCAS180_slice_shadower3_OUTS[2] & ISCAS180_slice_shadower3_OUTS[3]) | ISCAS180_slice_shadower3_OUTS[4]) | ISCAS180_slice_shadower3_OUTS[5]);
assign ISCAS180_highorderAC3_AC630_out1 = (((ISCAS180_slice_shadower3_OUTS[4] & ISCAS180_slice_shadower3_OUTS[5]) | ISCAS180_slice_shadower3_OUTS[0]) | ISCAS180_slice_shadower3_OUTS[1]);



assign ISCAS180_highorderAC3_OUTS = ISCAS180_highorderAC3_outs_vec;



assign ISCAS180_slice_shadower4_OUTS = ISCAS180_slice_shadower4_INPUTS;



assign ISCAS180_highorderAC4_AC321_out2 = ((ISCAS180_slice_shadower4_OUTS[0] & ISCAS180_slice_shadower4_OUTS[1]) | ISCAS180_slice_shadower4_OUTS[2]);
assign ISCAS180_highorderAC4_AC321_out1 = (ISCAS180_slice_shadower4_OUTS[0] | ISCAS180_slice_shadower4_OUTS[1]);



assign ISCAS180_highorderAC4_AC421_out2 = (((ISCAS180_slice_shadower4_OUTS[3] & ISCAS180_slice_shadower4_OUTS[4]) | ISCAS180_slice_shadower4_OUTS[5]) | ISCAS180_slice_shadower4_OUTS[6]);
assign ISCAS180_highorderAC4_AC421_out1 = (((ISCAS180_slice_shadower4_OUTS[5] & ISCAS180_slice_shadower4_OUTS[6]) | ISCAS180_slice_shadower4_OUTS[3]) | ISCAS180_slice_shadower4_OUTS[4]);



assign ISCAS180_highorderAC4_OUTS = ISCAS180_highorderAC4_outs_vec;



assign ISCAS180_slice_shadower5_OUTS = ISCAS180_slice_shadower5_INPUTS;



assign ISCAS180_highorderAC5_AC422_out2 = (((ISCAS180_slice_shadower5_OUTS[0] & ISCAS180_slice_shadower5_OUTS[1]) | ISCAS180_slice_shadower5_OUTS[2]) | ISCAS180_slice_shadower5_OUTS[3]);
assign ISCAS180_highorderAC5_AC422_out1 = (((ISCAS180_slice_shadower5_OUTS[2] & ISCAS180_slice_shadower5_OUTS[3]) | ISCAS180_slice_shadower5_OUTS[0]) | ISCAS180_slice_shadower5_OUTS[1]);



assign ISCAS180_highorderAC5_AC423_out2 = (((ISCAS180_slice_shadower5_OUTS[4] & ISCAS180_slice_shadower5_OUTS[5]) | ISCAS180_slice_shadower5_OUTS[6]) | ISCAS180_slice_shadower5_OUTS[7]);
assign ISCAS180_highorderAC5_AC423_out1 = (((ISCAS180_slice_shadower5_OUTS[6] & ISCAS180_slice_shadower5_OUTS[7]) | ISCAS180_slice_shadower5_OUTS[4]) | ISCAS180_slice_shadower5_OUTS[5]);



assign ISCAS180_highorderAC5_OUTS = ISCAS180_highorderAC5_outs_vec;



assign ISCAS180_slice_shadower6_OUTS = ISCAS180_slice_shadower6_INPUTS;



assign ISCAS180_highorderAC6_AC424_out2 = (((ISCAS180_slice_shadower6_OUTS[0] & ISCAS180_slice_shadower6_OUTS[1]) | ISCAS180_slice_shadower6_OUTS[2]) | ISCAS180_slice_shadower6_OUTS[3]);
assign ISCAS180_highorderAC6_AC424_out1 = (((ISCAS180_slice_shadower6_OUTS[2] & ISCAS180_slice_shadower6_OUTS[3]) | ISCAS180_slice_shadower6_OUTS[0]) | ISCAS180_slice_shadower6_OUTS[1]);



assign ISCAS180_highorderAC6_AC531_out3 = (((ISCAS180_slice_shadower6_OUTS[4] & ISCAS180_slice_shadower6_OUTS[5]) | ISCAS180_slice_shadower6_OUTS[6]) | ISCAS180_slice_shadower6_OUTS[7]);
assign ISCAS180_highorderAC6_AC531_out2 = (ISCAS180_slice_shadower6_OUTS[4] | ISCAS180_slice_shadower6_OUTS[5]);
assign ISCAS180_highorderAC6_AC531_out1 = ((ISCAS180_slice_shadower6_OUTS[6] & ISCAS180_slice_shadower6_OUTS[7]) | ISCAS180_slice_shadower6_OUTS[8]);



assign ISCAS180_highorderAC6_OUTS = ISCAS180_highorderAC6_outs_vec;



assign ISCAS180_slice_shadower7_OUTS = ISCAS180_slice_shadower7_INPUTS;



assign ISCAS180_highorderAC7_AC425_out2 = (((ISCAS180_slice_shadower7_OUTS[0] & ISCAS180_slice_shadower7_OUTS[1]) | ISCAS180_slice_shadower7_OUTS[2]) | ISCAS180_slice_shadower7_OUTS[3]);
assign ISCAS180_highorderAC7_AC425_out1 = (((ISCAS180_slice_shadower7_OUTS[2] & ISCAS180_slice_shadower7_OUTS[3]) | ISCAS180_slice_shadower7_OUTS[0]) | ISCAS180_slice_shadower7_OUTS[1]);



assign ISCAS180_highorderAC7_AC631_out3 = (((ISCAS180_slice_shadower7_OUTS[4] & ISCAS180_slice_shadower7_OUTS[5]) | ISCAS180_slice_shadower7_OUTS[6]) | ISCAS180_slice_shadower7_OUTS[7]);
assign ISCAS180_highorderAC7_AC631_out2 = (((ISCAS180_slice_shadower7_OUTS[6] & ISCAS180_slice_shadower7_OUTS[7]) | ISCAS180_slice_shadower7_OUTS[8]) | ISCAS180_slice_shadower7_OUTS[9]);
assign ISCAS180_highorderAC7_AC631_out1 = (((ISCAS180_slice_shadower7_OUTS[8] & ISCAS180_slice_shadower7_OUTS[9]) | ISCAS180_slice_shadower7_OUTS[4]) | ISCAS180_slice_shadower7_OUTS[5]);



assign ISCAS180_highorderAC7_OUTS = ISCAS180_highorderAC7_outs_vec;



assign ISCAS180_slice_shadower8_OUTS = ISCAS180_slice_shadower8_INPUTS;



assign ISCAS180_highorderAC8_AC322_out2 = ((ISCAS180_slice_shadower8_OUTS[0] & ISCAS180_slice_shadower8_OUTS[1]) | ISCAS180_slice_shadower8_OUTS[2]);
assign ISCAS180_highorderAC8_AC322_out1 = (ISCAS180_slice_shadower8_OUTS[0] | ISCAS180_slice_shadower8_OUTS[1]);



assign ISCAS180_highorderAC8_AC426_out2 = (((ISCAS180_slice_shadower8_OUTS[3] & ISCAS180_slice_shadower8_OUTS[4]) | ISCAS180_slice_shadower8_OUTS[5]) | ISCAS180_slice_shadower8_OUTS[6]);
assign ISCAS180_highorderAC8_AC426_out1 = (((ISCAS180_slice_shadower8_OUTS[5] & ISCAS180_slice_shadower8_OUTS[6]) | ISCAS180_slice_shadower8_OUTS[3]) | ISCAS180_slice_shadower8_OUTS[4]);



assign ISCAS180_highorderAC8_AC427_out2 = (((ISCAS180_slice_shadower8_OUTS[7] & ISCAS180_slice_shadower8_OUTS[8]) | ISCAS180_slice_shadower8_OUTS[9]) | ISCAS180_slice_shadower8_OUTS[10]);
assign ISCAS180_highorderAC8_AC427_out1 = (((ISCAS180_slice_shadower8_OUTS[9] & ISCAS180_slice_shadower8_OUTS[10]) | ISCAS180_slice_shadower8_OUTS[7]) | ISCAS180_slice_shadower8_OUTS[8]);



assign ISCAS180_highorderAC8_OUTS = ISCAS180_highorderAC8_outs_vec;



assign ISCAS180_slice_shadower9_OUTS = ISCAS180_slice_shadower9_INPUTS;



assign ISCAS180_highorderAC9_AC428_out2 = (((ISCAS180_slice_shadower9_OUTS[0] & ISCAS180_slice_shadower9_OUTS[1]) | ISCAS180_slice_shadower9_OUTS[2]) | ISCAS180_slice_shadower9_OUTS[3]);
assign ISCAS180_highorderAC9_AC428_out1 = (((ISCAS180_slice_shadower9_OUTS[2] & ISCAS180_slice_shadower9_OUTS[3]) | ISCAS180_slice_shadower9_OUTS[0]) | ISCAS180_slice_shadower9_OUTS[1]);



assign ISCAS180_highorderAC9_AC429_out2 = (((ISCAS180_slice_shadower9_OUTS[4] & ISCAS180_slice_shadower9_OUTS[5]) | ISCAS180_slice_shadower9_OUTS[6]) | ISCAS180_slice_shadower9_OUTS[7]);
assign ISCAS180_highorderAC9_AC429_out1 = (((ISCAS180_slice_shadower9_OUTS[6] & ISCAS180_slice_shadower9_OUTS[7]) | ISCAS180_slice_shadower9_OUTS[4]) | ISCAS180_slice_shadower9_OUTS[5]);



assign ISCAS180_highorderAC9_AC4210_out2 = (((ISCAS180_slice_shadower9_OUTS[8] & ISCAS180_slice_shadower9_OUTS[9]) | ISCAS180_slice_shadower9_OUTS[10]) | ISCAS180_slice_shadower9_OUTS[11]);
assign ISCAS180_highorderAC9_AC4210_out1 = (((ISCAS180_slice_shadower9_OUTS[10] & ISCAS180_slice_shadower9_OUTS[11]) | ISCAS180_slice_shadower9_OUTS[8]) | ISCAS180_slice_shadower9_OUTS[9]);



assign ISCAS180_highorderAC9_OUTS = ISCAS180_highorderAC9_outs_vec;



assign ISCAS180_slice_shadower10_OUTS = ISCAS180_slice_shadower10_INPUTS;



assign ISCAS180_highorderAC10_AC323_out2 = ((ISCAS180_slice_shadower10_OUTS[0] & ISCAS180_slice_shadower10_OUTS[1]) | ISCAS180_slice_shadower10_OUTS[2]);
assign ISCAS180_highorderAC10_AC323_out1 = (ISCAS180_slice_shadower10_OUTS[0] | ISCAS180_slice_shadower10_OUTS[1]);



assign ISCAS180_highorderAC10_AC4211_out2 = (((ISCAS180_slice_shadower10_OUTS[3] & ISCAS180_slice_shadower10_OUTS[4]) | ISCAS180_slice_shadower10_OUTS[5]) | ISCAS180_slice_shadower10_OUTS[6]);
assign ISCAS180_highorderAC10_AC4211_out1 = (((ISCAS180_slice_shadower10_OUTS[5] & ISCAS180_slice_shadower10_OUTS[6]) | ISCAS180_slice_shadower10_OUTS[3]) | ISCAS180_slice_shadower10_OUTS[4]);



assign ISCAS180_highorderAC10_AC4212_out2 = (((ISCAS180_slice_shadower10_OUTS[7] & ISCAS180_slice_shadower10_OUTS[8]) | ISCAS180_slice_shadower10_OUTS[9]) | ISCAS180_slice_shadower10_OUTS[10]);
assign ISCAS180_highorderAC10_AC4212_out1 = (((ISCAS180_slice_shadower10_OUTS[9] & ISCAS180_slice_shadower10_OUTS[10]) | ISCAS180_slice_shadower10_OUTS[7]) | ISCAS180_slice_shadower10_OUTS[8]);



assign ISCAS180_highorderAC10_OUTS = ISCAS180_highorderAC10_outs_vec;



assign ISCAS180_slice_shadower11_OUTS = ISCAS180_slice_shadower11_INPUTS;



assign ISCAS180_highorderAC11_AC4213_out2 = (((ISCAS180_slice_shadower11_OUTS[0] & ISCAS180_slice_shadower11_OUTS[1]) | ISCAS180_slice_shadower11_OUTS[2]) | ISCAS180_slice_shadower11_OUTS[3]);
assign ISCAS180_highorderAC11_AC4213_out1 = (((ISCAS180_slice_shadower11_OUTS[2] & ISCAS180_slice_shadower11_OUTS[3]) | ISCAS180_slice_shadower11_OUTS[0]) | ISCAS180_slice_shadower11_OUTS[1]);



assign ISCAS180_highorderAC11_AC632_out3 = (((ISCAS180_slice_shadower11_OUTS[4] & ISCAS180_slice_shadower11_OUTS[5]) | ISCAS180_slice_shadower11_OUTS[6]) | ISCAS180_slice_shadower11_OUTS[7]);
assign ISCAS180_highorderAC11_AC632_out2 = (((ISCAS180_slice_shadower11_OUTS[6] & ISCAS180_slice_shadower11_OUTS[7]) | ISCAS180_slice_shadower11_OUTS[8]) | ISCAS180_slice_shadower11_OUTS[9]);
assign ISCAS180_highorderAC11_AC632_out1 = (((ISCAS180_slice_shadower11_OUTS[8] & ISCAS180_slice_shadower11_OUTS[9]) | ISCAS180_slice_shadower11_OUTS[4]) | ISCAS180_slice_shadower11_OUTS[5]);



assign ISCAS180_highorderAC11_OUTS = ISCAS180_highorderAC11_outs_vec;



assign ISCAS180_slice_shadower12_OUTS = ISCAS180_slice_shadower12_INPUTS;



assign ISCAS180_highorderAC12_AC4214_out2 = (((ISCAS180_slice_shadower12_OUTS[0] & ISCAS180_slice_shadower12_OUTS[1]) | ISCAS180_slice_shadower12_OUTS[2]) | ISCAS180_slice_shadower12_OUTS[3]);
assign ISCAS180_highorderAC12_AC4214_out1 = (((ISCAS180_slice_shadower12_OUTS[2] & ISCAS180_slice_shadower12_OUTS[3]) | ISCAS180_slice_shadower12_OUTS[0]) | ISCAS180_slice_shadower12_OUTS[1]);



assign ISCAS180_highorderAC12_AC532_out3 = (((ISCAS180_slice_shadower12_OUTS[4] & ISCAS180_slice_shadower12_OUTS[5]) | ISCAS180_slice_shadower12_OUTS[6]) | ISCAS180_slice_shadower12_OUTS[7]);
assign ISCAS180_highorderAC12_AC532_out2 = (ISCAS180_slice_shadower12_OUTS[4] | ISCAS180_slice_shadower12_OUTS[5]);
assign ISCAS180_highorderAC12_AC532_out1 = ((ISCAS180_slice_shadower12_OUTS[6] & ISCAS180_slice_shadower12_OUTS[7]) | ISCAS180_slice_shadower12_OUTS[8]);



assign ISCAS180_highorderAC12_OUTS = ISCAS180_highorderAC12_outs_vec;



assign ISCAS180_slice_shadower13_OUTS = ISCAS180_slice_shadower13_INPUTS;



assign ISCAS180_highorderAC13_AC4215_out2 = (((ISCAS180_slice_shadower13_OUTS[0] & ISCAS180_slice_shadower13_OUTS[1]) | ISCAS180_slice_shadower13_OUTS[2]) | ISCAS180_slice_shadower13_OUTS[3]);
assign ISCAS180_highorderAC13_AC4215_out1 = (((ISCAS180_slice_shadower13_OUTS[2] & ISCAS180_slice_shadower13_OUTS[3]) | ISCAS180_slice_shadower13_OUTS[0]) | ISCAS180_slice_shadower13_OUTS[1]);



assign ISCAS180_highorderAC13_AC4216_out2 = (((ISCAS180_slice_shadower13_OUTS[4] & ISCAS180_slice_shadower13_OUTS[5]) | ISCAS180_slice_shadower13_OUTS[6]) | ISCAS180_slice_shadower13_OUTS[7]);
assign ISCAS180_highorderAC13_AC4216_out1 = (((ISCAS180_slice_shadower13_OUTS[6] & ISCAS180_slice_shadower13_OUTS[7]) | ISCAS180_slice_shadower13_OUTS[4]) | ISCAS180_slice_shadower13_OUTS[5]);



assign ISCAS180_highorderAC13_OUTS = ISCAS180_highorderAC13_outs_vec;



assign ISCAS180_FA0_sum = ((OutBits_ppg[116] ^ OutBits_ppg[117]) ^ OutBits_ppg[118]);
assign ISCAS180_FA0_cout = (((OutBits_ppg[116] & OutBits_ppg[117]) | (OutBits_ppg[116] & OutBits_ppg[118])) | (OutBits_ppg[117] & OutBits_ppg[118]));



assign ISCAS180_FA1_sum = ((OutBits_ppg[119] ^ OutBits_ppg[120]) ^ OutBits_ppg[121]);
assign ISCAS180_FA1_cout = (((OutBits_ppg[119] & OutBits_ppg[120]) | (OutBits_ppg[119] & OutBits_ppg[121])) | (OutBits_ppg[120] & OutBits_ppg[121]));



assign ISCAS180_FA2_sum = ((ISCAS180_FA0_cout ^ ISCAS180_FA1_cout) ^ OutBits_ppg[123]);
assign ISCAS180_FA2_cout = (((ISCAS180_FA0_cout & ISCAS180_FA1_cout) | (ISCAS180_FA0_cout & OutBits_ppg[123])) | (ISCAS180_FA1_cout & OutBits_ppg[123]));



assign ISCAS180_FA3_sum = ((OutBits_ppg[124] ^ OutBits_ppg[125]) ^ OutBits_ppg[126]);
assign ISCAS180_FA3_cout = (((OutBits_ppg[124] & OutBits_ppg[125]) | (OutBits_ppg[124] & OutBits_ppg[126])) | (OutBits_ppg[125] & OutBits_ppg[126]));



assign ISCAS180_FA4_sum = ((ISCAS180_FA2_cout ^ ISCAS180_FA3_cout) ^ OutBits_ppg[129]);
assign ISCAS180_FA4_cout = (((ISCAS180_FA2_cout & ISCAS180_FA3_cout) | (ISCAS180_FA2_cout & OutBits_ppg[129])) | (ISCAS180_FA3_cout & OutBits_ppg[129]));



assign ISCAS180_FA5_sum = ((OutBits_ppg[130] ^ OutBits_ppg[131]) ^ OutBits_ppg[132]);
assign ISCAS180_FA5_cout = (((OutBits_ppg[130] & OutBits_ppg[131]) | (OutBits_ppg[130] & OutBits_ppg[132])) | (OutBits_ppg[131] & OutBits_ppg[132]));



assign ISCAS180_FA6_sum = ((ISCAS180_FA4_cout ^ ISCAS180_FA5_cout) ^ OutBits_ppg[134]);
assign ISCAS180_FA6_cout = (((ISCAS180_FA4_cout & ISCAS180_FA5_cout) | (ISCAS180_FA4_cout & OutBits_ppg[134])) | (ISCAS180_FA5_cout & OutBits_ppg[134]));



assign ISCAS180_FA7_sum = ((OutBits_ppg[135] ^ OutBits_ppg[136]) ^ OutBits_ppg[137]);
assign ISCAS180_FA7_cout = (((OutBits_ppg[135] & OutBits_ppg[136]) | (OutBits_ppg[135] & OutBits_ppg[137])) | (OutBits_ppg[136] & OutBits_ppg[137]));



assign ISCAS180_FA8_sum = ((ISCAS180_FA6_cout ^ ISCAS180_FA7_cout) ^ OutBits_ppg[138]);
assign ISCAS180_FA8_cout = (((ISCAS180_FA6_cout & ISCAS180_FA7_cout) | (ISCAS180_FA6_cout & OutBits_ppg[138])) | (ISCAS180_FA7_cout & OutBits_ppg[138]));



assign ISCAS180_FA9_sum = ((ISCAS180_FA8_cout ^ OutBits_ppg[141]) ^ OutBits_ppg[142]);
assign ISCAS180_FA9_cout = (((ISCAS180_FA8_cout & OutBits_ppg[141]) | (ISCAS180_FA8_cout & OutBits_ppg[142])) | (OutBits_ppg[141] & OutBits_ppg[142]));



assign ISCAS180_slice_shadower14_OUTS = ISCAS180_slice_shadower14_INPUTS;



assign ISCAS180_highorderAC14_AC324_out2 = ((ISCAS180_slice_shadower14_OUTS[0] & ISCAS180_slice_shadower14_OUTS[1]) | ISCAS180_slice_shadower14_OUTS[2]);
assign ISCAS180_highorderAC14_AC324_out1 = (ISCAS180_slice_shadower14_OUTS[0] | ISCAS180_slice_shadower14_OUTS[1]);



assign ISCAS180_highorderAC14_OUTS = ISCAS180_highorderAC14_outs_vec;



assign ISCAS180_slice_shadower15_OUTS = ISCAS180_slice_shadower15_INPUTS;



assign ISCAS180_highorderAC15_AC325_out2 = ((ISCAS180_slice_shadower15_OUTS[0] & ISCAS180_slice_shadower15_OUTS[1]) | ISCAS180_slice_shadower15_OUTS[2]);
assign ISCAS180_highorderAC15_AC325_out1 = (ISCAS180_slice_shadower15_OUTS[0] | ISCAS180_slice_shadower15_OUTS[1]);



assign ISCAS180_highorderAC15_OUTS = ISCAS180_highorderAC15_outs_vec;



assign ISCAS180_slice_shadower16_OUTS = ISCAS180_slice_shadower16_INPUTS;



assign ISCAS180_highorderAC16_AC4217_out2 = (((ISCAS180_slice_shadower16_OUTS[0] & ISCAS180_slice_shadower16_OUTS[1]) | ISCAS180_slice_shadower16_OUTS[2]) | ISCAS180_slice_shadower16_OUTS[3]);
assign ISCAS180_highorderAC16_AC4217_out1 = (((ISCAS180_slice_shadower16_OUTS[2] & ISCAS180_slice_shadower16_OUTS[3]) | ISCAS180_slice_shadower16_OUTS[0]) | ISCAS180_slice_shadower16_OUTS[1]);



assign ISCAS180_highorderAC16_OUTS = ISCAS180_highorderAC16_outs_vec;



assign ISCAS180_slice_shadower17_OUTS = ISCAS180_slice_shadower17_INPUTS;



assign ISCAS180_highorderAC17_AC4218_out2 = (((ISCAS180_slice_shadower17_OUTS[0] & ISCAS180_slice_shadower17_OUTS[1]) | ISCAS180_slice_shadower17_OUTS[2]) | ISCAS180_slice_shadower17_OUTS[3]);
assign ISCAS180_highorderAC17_AC4218_out1 = (((ISCAS180_slice_shadower17_OUTS[2] & ISCAS180_slice_shadower17_OUTS[3]) | ISCAS180_slice_shadower17_OUTS[0]) | ISCAS180_slice_shadower17_OUTS[1]);



assign ISCAS180_highorderAC17_OUTS = ISCAS180_highorderAC17_outs_vec;



assign ISCAS180_slice_shadower18_OUTS = ISCAS180_slice_shadower18_INPUTS;



assign ISCAS180_highorderAC18_AC533_out3 = (((ISCAS180_slice_shadower18_OUTS[0] & ISCAS180_slice_shadower18_OUTS[1]) | ISCAS180_slice_shadower18_OUTS[2]) | ISCAS180_slice_shadower18_OUTS[3]);
assign ISCAS180_highorderAC18_AC533_out2 = (ISCAS180_slice_shadower18_OUTS[0] | ISCAS180_slice_shadower18_OUTS[1]);
assign ISCAS180_highorderAC18_AC533_out1 = ((ISCAS180_slice_shadower18_OUTS[2] & ISCAS180_slice_shadower18_OUTS[3]) | ISCAS180_slice_shadower18_OUTS[4]);



assign ISCAS180_highorderAC18_OUTS = ISCAS180_highorderAC18_outs_vec;



assign ISCAS180_slice_shadower19_OUTS = ISCAS180_slice_shadower19_INPUTS;



assign ISCAS180_highorderAC19_AC534_out3 = (((ISCAS180_slice_shadower19_OUTS[0] & ISCAS180_slice_shadower19_OUTS[1]) | ISCAS180_slice_shadower19_OUTS[2]) | ISCAS180_slice_shadower19_OUTS[3]);
assign ISCAS180_highorderAC19_AC534_out2 = (ISCAS180_slice_shadower19_OUTS[0] | ISCAS180_slice_shadower19_OUTS[1]);
assign ISCAS180_highorderAC19_AC534_out1 = ((ISCAS180_slice_shadower19_OUTS[2] & ISCAS180_slice_shadower19_OUTS[3]) | ISCAS180_slice_shadower19_OUTS[4]);



assign ISCAS180_highorderAC19_OUTS = ISCAS180_highorderAC19_outs_vec;



assign ISCAS180_slice_shadower20_OUTS = ISCAS180_slice_shadower20_INPUTS;



assign ISCAS180_highorderAC20_AC633_out3 = (((ISCAS180_slice_shadower20_OUTS[0] & ISCAS180_slice_shadower20_OUTS[1]) | ISCAS180_slice_shadower20_OUTS[2]) | ISCAS180_slice_shadower20_OUTS[3]);
assign ISCAS180_highorderAC20_AC633_out2 = (((ISCAS180_slice_shadower20_OUTS[2] & ISCAS180_slice_shadower20_OUTS[3]) | ISCAS180_slice_shadower20_OUTS[4]) | ISCAS180_slice_shadower20_OUTS[5]);
assign ISCAS180_highorderAC20_AC633_out1 = (((ISCAS180_slice_shadower20_OUTS[4] & ISCAS180_slice_shadower20_OUTS[5]) | ISCAS180_slice_shadower20_OUTS[0]) | ISCAS180_slice_shadower20_OUTS[1]);



assign ISCAS180_highorderAC20_OUTS = ISCAS180_highorderAC20_outs_vec;



assign ISCAS180_slice_shadower21_OUTS = ISCAS180_slice_shadower21_INPUTS;



assign ISCAS180_highorderAC21_AC634_out3 = (((ISCAS180_slice_shadower21_OUTS[0] & ISCAS180_slice_shadower21_OUTS[1]) | ISCAS180_slice_shadower21_OUTS[2]) | ISCAS180_slice_shadower21_OUTS[3]);
assign ISCAS180_highorderAC21_AC634_out2 = (((ISCAS180_slice_shadower21_OUTS[2] & ISCAS180_slice_shadower21_OUTS[3]) | ISCAS180_slice_shadower21_OUTS[4]) | ISCAS180_slice_shadower21_OUTS[5]);
assign ISCAS180_highorderAC21_AC634_out1 = (((ISCAS180_slice_shadower21_OUTS[4] & ISCAS180_slice_shadower21_OUTS[5]) | ISCAS180_slice_shadower21_OUTS[0]) | ISCAS180_slice_shadower21_OUTS[1]);



assign ISCAS180_highorderAC21_OUTS = ISCAS180_highorderAC21_outs_vec;



assign ISCAS180_slice_shadower22_OUTS = ISCAS180_slice_shadower22_INPUTS;



assign ISCAS180_highorderAC22_AC635_out3 = (((ISCAS180_slice_shadower22_OUTS[0] & ISCAS180_slice_shadower22_OUTS[1]) | ISCAS180_slice_shadower22_OUTS[2]) | ISCAS180_slice_shadower22_OUTS[3]);
assign ISCAS180_highorderAC22_AC635_out2 = (((ISCAS180_slice_shadower22_OUTS[2] & ISCAS180_slice_shadower22_OUTS[3]) | ISCAS180_slice_shadower22_OUTS[4]) | ISCAS180_slice_shadower22_OUTS[5]);
assign ISCAS180_highorderAC22_AC635_out1 = (((ISCAS180_slice_shadower22_OUTS[4] & ISCAS180_slice_shadower22_OUTS[5]) | ISCAS180_slice_shadower22_OUTS[0]) | ISCAS180_slice_shadower22_OUTS[1]);



assign ISCAS180_highorderAC22_OUTS = ISCAS180_highorderAC22_outs_vec;



assign ISCAS180_slice_shadower23_OUTS = ISCAS180_slice_shadower23_INPUTS;



assign ISCAS180_highorderAC23_AC535_out3 = (((ISCAS180_slice_shadower23_OUTS[0] & ISCAS180_slice_shadower23_OUTS[1]) | ISCAS180_slice_shadower23_OUTS[2]) | ISCAS180_slice_shadower23_OUTS[3]);
assign ISCAS180_highorderAC23_AC535_out2 = (ISCAS180_slice_shadower23_OUTS[0] | ISCAS180_slice_shadower23_OUTS[1]);
assign ISCAS180_highorderAC23_AC535_out1 = ((ISCAS180_slice_shadower23_OUTS[2] & ISCAS180_slice_shadower23_OUTS[3]) | ISCAS180_slice_shadower23_OUTS[4]);



assign ISCAS180_highorderAC23_OUTS = ISCAS180_highorderAC23_outs_vec;



assign ISCAS180_slice_shadower24_OUTS = ISCAS180_slice_shadower24_INPUTS;



assign ISCAS180_highorderAC24_AC536_out3 = (((ISCAS180_slice_shadower24_OUTS[0] & ISCAS180_slice_shadower24_OUTS[1]) | ISCAS180_slice_shadower24_OUTS[2]) | ISCAS180_slice_shadower24_OUTS[3]);
assign ISCAS180_highorderAC24_AC536_out2 = (ISCAS180_slice_shadower24_OUTS[0] | ISCAS180_slice_shadower24_OUTS[1]);
assign ISCAS180_highorderAC24_AC536_out1 = ((ISCAS180_slice_shadower24_OUTS[2] & ISCAS180_slice_shadower24_OUTS[3]) | ISCAS180_slice_shadower24_OUTS[4]);



assign ISCAS180_highorderAC24_OUTS = ISCAS180_highorderAC24_outs_vec;



assign ISCAS180_slice_shadower25_OUTS = ISCAS180_slice_shadower25_INPUTS;



assign ISCAS180_highorderAC25_AC4219_out2 = (((ISCAS180_slice_shadower25_OUTS[0] & ISCAS180_slice_shadower25_OUTS[1]) | ISCAS180_slice_shadower25_OUTS[2]) | ISCAS180_slice_shadower25_OUTS[3]);
assign ISCAS180_highorderAC25_AC4219_out1 = (((ISCAS180_slice_shadower25_OUTS[2] & ISCAS180_slice_shadower25_OUTS[3]) | ISCAS180_slice_shadower25_OUTS[0]) | ISCAS180_slice_shadower25_OUTS[1]);



assign ISCAS180_highorderAC25_OUTS = ISCAS180_highorderAC25_outs_vec;



assign ISCAS180_HA0_sum = (ISCAS180_FA2_sum ^ ISCAS180_FA3_sum);
assign ISCAS180_HA0_cout = (ISCAS180_FA2_sum & ISCAS180_FA3_sum);



assign ISCAS180_HA1_sum = (ISCAS180_HA0_cout ^ ISCAS180_FA4_sum);
assign ISCAS180_HA1_cout = (ISCAS180_HA0_cout & ISCAS180_FA4_sum);



assign ISCAS180_HA2_sum = (ISCAS180_highorderAC18_OUTS[0] ^ ISCAS180_highorderAC18_OUTS[1]);
assign ISCAS180_HA2_cout = (ISCAS180_highorderAC18_OUTS[0] & ISCAS180_highorderAC18_OUTS[1]);



assign ISCAS180_FA10_sum = ((ISCAS180_highorderAC19_OUTS[0] ^ ISCAS180_highorderAC19_OUTS[1]) ^ ISCAS180_highorderAC19_OUTS[2]);
assign ISCAS180_FA10_cout = (((ISCAS180_highorderAC19_OUTS[0] & ISCAS180_highorderAC19_OUTS[1]) | (ISCAS180_highorderAC19_OUTS[0] & ISCAS180_highorderAC19_OUTS[2])) | (ISCAS180_highorderAC19_OUTS[1] & ISCAS180_highorderAC19_OUTS[2]));



assign ISCAS180_FA11_sum = ((ISCAS180_highorderAC20_OUTS[0] ^ ISCAS180_highorderAC20_OUTS[1]) ^ ISCAS180_highorderAC20_OUTS[2]);
assign ISCAS180_FA11_cout = (((ISCAS180_highorderAC20_OUTS[0] & ISCAS180_highorderAC20_OUTS[1]) | (ISCAS180_highorderAC20_OUTS[0] & ISCAS180_highorderAC20_OUTS[2])) | (ISCAS180_highorderAC20_OUTS[1] & ISCAS180_highorderAC20_OUTS[2]));



assign ISCAS180_FA12_sum = ((ISCAS180_highorderAC21_OUTS[0] ^ ISCAS180_highorderAC21_OUTS[1]) ^ ISCAS180_highorderAC21_OUTS[2]);
assign ISCAS180_FA12_cout = (((ISCAS180_highorderAC21_OUTS[0] & ISCAS180_highorderAC21_OUTS[1]) | (ISCAS180_highorderAC21_OUTS[0] & ISCAS180_highorderAC21_OUTS[2])) | (ISCAS180_highorderAC21_OUTS[1] & ISCAS180_highorderAC21_OUTS[2]));



assign ISCAS180_FA13_sum = ((ISCAS180_highorderAC22_OUTS[0] ^ ISCAS180_highorderAC22_OUTS[1]) ^ ISCAS180_highorderAC22_OUTS[2]);
assign ISCAS180_FA13_cout = (((ISCAS180_highorderAC22_OUTS[0] & ISCAS180_highorderAC22_OUTS[1]) | (ISCAS180_highorderAC22_OUTS[0] & ISCAS180_highorderAC22_OUTS[2])) | (ISCAS180_highorderAC22_OUTS[1] & ISCAS180_highorderAC22_OUTS[2]));



assign ISCAS180_FA14_sum = ((ISCAS180_highorderAC23_OUTS[0] ^ ISCAS180_highorderAC23_OUTS[1]) ^ ISCAS180_highorderAC23_OUTS[2]);
assign ISCAS180_FA14_cout = (((ISCAS180_highorderAC23_OUTS[0] & ISCAS180_highorderAC23_OUTS[1]) | (ISCAS180_highorderAC23_OUTS[0] & ISCAS180_highorderAC23_OUTS[2])) | (ISCAS180_highorderAC23_OUTS[1] & ISCAS180_highorderAC23_OUTS[2]));



assign ISCAS180_FA15_sum = ((ISCAS180_highorderAC24_OUTS[0] ^ ISCAS180_highorderAC24_OUTS[1]) ^ ISCAS180_highorderAC24_OUTS[2]);
assign ISCAS180_FA15_cout = (((ISCAS180_highorderAC24_OUTS[0] & ISCAS180_highorderAC24_OUTS[1]) | (ISCAS180_highorderAC24_OUTS[0] & ISCAS180_highorderAC24_OUTS[2])) | (ISCAS180_highorderAC24_OUTS[1] & ISCAS180_highorderAC24_OUTS[2]));



assign ISCAS180_HA3_sum = (ISCAS180_highorderAC25_OUTS[0] ^ ISCAS180_highorderAC25_OUTS[1]);
assign ISCAS180_HA3_cout = (ISCAS180_highorderAC25_OUTS[0] & ISCAS180_highorderAC25_OUTS[1]);



assign ISCAS180_FA16_sum = ((ISCAS180_FA0_sum ^ ISCAS180_FA1_sum) ^ OutBits_ppg[122]);
assign ISCAS180_FA16_cout = (((ISCAS180_FA0_sum & ISCAS180_FA1_sum) | (ISCAS180_FA0_sum & OutBits_ppg[122])) | (ISCAS180_FA1_sum & OutBits_ppg[122]));



assign ISCAS180_FA17_sum = ((ISCAS180_HA0_sum ^ OutBits_ppg[127]) ^ OutBits_ppg[128]);
assign ISCAS180_FA17_cout = (((ISCAS180_HA0_sum & OutBits_ppg[127]) | (ISCAS180_HA0_sum & OutBits_ppg[128])) | (OutBits_ppg[127] & OutBits_ppg[128]));



assign ISCAS180_FA18_sum = ((ISCAS180_HA1_sum ^ ISCAS180_FA5_sum) ^ OutBits_ppg[133]);
assign ISCAS180_FA18_cout = (((ISCAS180_HA1_sum & ISCAS180_FA5_sum) | (ISCAS180_HA1_sum & OutBits_ppg[133])) | (ISCAS180_FA5_sum & OutBits_ppg[133]));



assign ISCAS180_FA19_sum = ((ISCAS180_HA1_cout ^ ISCAS180_FA6_sum) ^ ISCAS180_FA7_sum);
assign ISCAS180_FA19_cout = (((ISCAS180_HA1_cout & ISCAS180_FA6_sum) | (ISCAS180_HA1_cout & ISCAS180_FA7_sum)) | (ISCAS180_FA6_sum & ISCAS180_FA7_sum));



assign ISCAS180_FA20_sum = ((ISCAS180_FA8_sum ^ OutBits_ppg[139]) ^ OutBits_ppg[140]);
assign ISCAS180_FA20_cout = (((ISCAS180_FA8_sum & OutBits_ppg[139]) | (ISCAS180_FA8_sum & OutBits_ppg[140])) | (OutBits_ppg[139] & OutBits_ppg[140]));



assign OUTS = ISCAS180_outs_vec;

endmodule
