// File: FA.v
// Generated by MyHDL 0.11
// Date: Tue Jul 27 17:45:35 2021


`timescale 1ns/10ps

module FA (
    cout,
    sum,
    a,
    b,
    c
);


output cout;
wire cout;
output sum;
wire sum;
input a;
input b;
input c;





assign sum = ((a ^ b) ^ c);
assign cout = (((a & b) | (a & c)) | (b & c));

endmodule
