// File: Multiplier.v
// Generated by MyHDL 0.11
// Date: Wed Aug 25 12:16:46 2021


`timescale 1ns/10ps

module Multiplier (
    A,
    B,
    OUTS
);


input [7:0] A;
input [7:0] B;
output [28:0] OUTS;
wire [28:0] OUTS;

wire [63:0] OutBits_ppg;
wire [63:0] PPG0_outs_vec;
wire [0:0] PPG0_AND0_out;
wire [0:0] PPG0_AND1_out;
wire [0:0] PPG0_AND2_out;
wire [0:0] PPG0_AND3_out;
wire [0:0] PPG0_AND4_out;
wire [0:0] PPG0_AND5_out;
wire [0:0] PPG0_AND6_out;
wire [0:0] PPG0_AND7_out;
wire [0:0] PPG0_AND8_out;
wire [0:0] PPG0_AND9_out;
wire [0:0] PPG0_AND10_out;
wire [0:0] PPG0_AND11_out;
wire [0:0] PPG0_AND12_out;
wire [0:0] PPG0_AND13_out;
wire [0:0] PPG0_AND14_out;
wire [0:0] PPG0_AND15_out;
wire [0:0] PPG0_AND16_out;
wire [0:0] PPG0_AND17_out;
wire [0:0] PPG0_AND18_out;
wire [0:0] PPG0_AND19_out;
wire [0:0] PPG0_AND20_out;
wire [0:0] PPG0_AND21_out;
wire [0:0] PPG0_AND22_out;
wire [0:0] PPG0_AND23_out;
wire [0:0] PPG0_AND24_out;
wire [0:0] PPG0_AND25_out;
wire [0:0] PPG0_AND26_out;
wire [0:0] PPG0_AND27_out;
wire [0:0] PPG0_AND28_out;
wire [0:0] PPG0_AND29_out;
wire [0:0] PPG0_AND30_out;
wire [0:0] PPG0_AND31_out;
wire [0:0] PPG0_AND32_out;
wire [0:0] PPG0_AND33_out;
wire [0:0] PPG0_AND34_out;
wire [0:0] PPG0_AND35_out;
wire [0:0] PPG0_AND36_out;
wire [0:0] PPG0_AND37_out;
wire [0:0] PPG0_AND38_out;
wire [0:0] PPG0_AND39_out;
wire [0:0] PPG0_AND40_out;
wire [0:0] PPG0_AND41_out;
wire [0:0] PPG0_AND42_out;
wire [0:0] PPG0_AND43_out;
wire [0:0] PPG0_AND44_out;
wire [0:0] PPG0_AND45_out;
wire [0:0] PPG0_AND46_out;
wire [0:0] PPG0_AND47_out;
wire [0:0] PPG0_AND48_out;
wire [0:0] PPG0_AND49_out;
wire [0:0] PPG0_AND50_out;
wire [0:0] PPG0_AND51_out;
wire [0:0] PPG0_AND52_out;
wire [0:0] PPG0_AND53_out;
wire [0:0] PPG0_AND54_out;
wire [0:0] PPG0_AND55_out;
wire [0:0] PPG0_AND56_out;
wire [0:0] PPG0_AND57_out;
wire [0:0] PPG0_AND58_out;
wire [0:0] PPG0_AND59_out;
wire [0:0] PPG0_AND60_out;
wire [0:0] PPG0_AND61_out;
wire [0:0] PPG0_AND62_out;
wire [0:0] PPG0_AND63_out;
wire [28:0] CompressorTree0_outs_vec;
wire [0:0] CompressorTree0_AC320_out1;
wire [0:0] CompressorTree0_AC320_out2;
wire [0:0] CompressorTree0_AC321_out1;
wire [0:0] CompressorTree0_AC321_out2;
wire [0:0] CompressorTree0_AC322_out1;
wire [0:0] CompressorTree0_AC322_out2;
wire [0:0] CompressorTree0_AC323_out1;
wire [0:0] CompressorTree0_AC323_out2;
wire [0:0] CompressorTree0_FA0_cout;
wire [0:0] CompressorTree0_FA0_sum;
wire [0:0] CompressorTree0_FA1_cout;
wire [0:0] CompressorTree0_FA1_sum;
wire [0:0] CompressorTree0_FA2_cout;
wire [0:0] CompressorTree0_FA2_sum;
wire [0:0] CompressorTree0_FA3_cout;
wire [0:0] CompressorTree0_FA3_sum;
wire [0:0] CompressorTree0_AC324_out1;
wire [0:0] CompressorTree0_AC324_out2;
wire [0:0] CompressorTree0_AC420_out1;
wire [0:0] CompressorTree0_AC420_out2;
wire [0:0] CompressorTree0_AC421_out1;
wire [0:0] CompressorTree0_AC421_out2;
wire [0:0] CompressorTree0_AC325_out1;
wire [0:0] CompressorTree0_AC325_out2;
wire [0:0] CompressorTree0_AC326_out1;
wire [0:0] CompressorTree0_AC326_out2;
wire [0:0] CompressorTree0_AC422_out1;
wire [0:0] CompressorTree0_AC422_out2;
wire [0:0] CompressorTree0_AC327_out1;
wire [0:0] CompressorTree0_AC327_out2;
wire [0:0] CompressorTree0_AC328_out1;
wire [0:0] CompressorTree0_AC328_out2;
wire [0:0] CompressorTree0_FA4_cout;
wire [0:0] CompressorTree0_FA4_sum;
wire [0:0] CompressorTree0_FA5_cout;
wire [0:0] CompressorTree0_FA5_sum;
wire [0:0] CompressorTree0_FA6_cout;
wire [0:0] CompressorTree0_FA6_sum;
wire [0:0] CompressorTree0_FA7_cout;
wire [0:0] CompressorTree0_FA7_sum;
wire [0:0] CompressorTree0_HA0_cout;
wire [0:0] CompressorTree0_HA0_sum;
wire [0:0] CompressorTree0_FA8_cout;
wire [0:0] CompressorTree0_FA8_sum;
wire [0:0] CompressorTree0_AC329_out1;
wire [0:0] CompressorTree0_AC329_out2;
wire [0:0] CompressorTree0_AC423_out1;
wire [0:0] CompressorTree0_AC423_out2;
wire [0:0] CompressorTree0_AC3210_out1;
wire [0:0] CompressorTree0_AC3210_out2;
wire [0:0] CompressorTree0_AC424_out1;
wire [0:0] CompressorTree0_AC424_out2;
wire [0:0] CompressorTree0_AC3211_out1;
wire [0:0] CompressorTree0_AC3211_out2;
wire [0:0] CompressorTree0_FA9_cout;
wire [0:0] CompressorTree0_FA9_sum;
wire [0:0] CompressorTree0_FA10_cout;
wire [0:0] CompressorTree0_FA10_sum;
wire [0:0] CompressorTree0_FA11_cout;
wire [0:0] CompressorTree0_FA11_sum;
wire [0:0] CompressorTree0_FA12_cout;
wire [0:0] CompressorTree0_FA12_sum;

assign PPG0_outs_vec[63] = PPG0_AND63_out[0];
assign PPG0_outs_vec[62] = PPG0_AND61_out[0];
assign PPG0_outs_vec[61] = PPG0_AND62_out[0];
assign PPG0_outs_vec[60] = PPG0_AND58_out[0];
assign PPG0_outs_vec[59] = PPG0_AND59_out[0];
assign PPG0_outs_vec[58] = PPG0_AND60_out[0];
assign PPG0_outs_vec[57] = PPG0_AND54_out[0];
assign PPG0_outs_vec[56] = PPG0_AND55_out[0];
assign PPG0_outs_vec[55] = PPG0_AND56_out[0];
assign PPG0_outs_vec[54] = PPG0_AND57_out[0];
assign PPG0_outs_vec[53] = PPG0_AND49_out[0];
assign PPG0_outs_vec[52] = PPG0_AND50_out[0];
assign PPG0_outs_vec[51] = PPG0_AND51_out[0];
assign PPG0_outs_vec[50] = PPG0_AND52_out[0];
assign PPG0_outs_vec[49] = PPG0_AND53_out[0];
assign PPG0_outs_vec[48] = PPG0_AND43_out[0];
assign PPG0_outs_vec[47] = PPG0_AND44_out[0];
assign PPG0_outs_vec[46] = PPG0_AND45_out[0];
assign PPG0_outs_vec[45] = PPG0_AND46_out[0];
assign PPG0_outs_vec[44] = PPG0_AND47_out[0];
assign PPG0_outs_vec[43] = PPG0_AND48_out[0];
assign PPG0_outs_vec[42] = PPG0_AND36_out[0];
assign PPG0_outs_vec[41] = PPG0_AND37_out[0];
assign PPG0_outs_vec[40] = PPG0_AND38_out[0];
assign PPG0_outs_vec[39] = PPG0_AND39_out[0];
assign PPG0_outs_vec[38] = PPG0_AND40_out[0];
assign PPG0_outs_vec[37] = PPG0_AND41_out[0];
assign PPG0_outs_vec[36] = PPG0_AND42_out[0];
assign PPG0_outs_vec[35] = PPG0_AND28_out[0];
assign PPG0_outs_vec[34] = PPG0_AND29_out[0];
assign PPG0_outs_vec[33] = PPG0_AND30_out[0];
assign PPG0_outs_vec[32] = PPG0_AND31_out[0];
assign PPG0_outs_vec[31] = PPG0_AND32_out[0];
assign PPG0_outs_vec[30] = PPG0_AND33_out[0];
assign PPG0_outs_vec[29] = PPG0_AND34_out[0];
assign PPG0_outs_vec[28] = PPG0_AND35_out[0];
assign PPG0_outs_vec[27] = PPG0_AND21_out[0];
assign PPG0_outs_vec[26] = PPG0_AND22_out[0];
assign PPG0_outs_vec[25] = PPG0_AND23_out[0];
assign PPG0_outs_vec[24] = PPG0_AND24_out[0];
assign PPG0_outs_vec[23] = PPG0_AND25_out[0];
assign PPG0_outs_vec[22] = PPG0_AND26_out[0];
assign PPG0_outs_vec[21] = PPG0_AND27_out[0];
assign PPG0_outs_vec[20] = PPG0_AND15_out[0];
assign PPG0_outs_vec[19] = PPG0_AND16_out[0];
assign PPG0_outs_vec[18] = PPG0_AND17_out[0];
assign PPG0_outs_vec[17] = PPG0_AND18_out[0];
assign PPG0_outs_vec[16] = PPG0_AND19_out[0];
assign PPG0_outs_vec[15] = PPG0_AND20_out[0];
assign PPG0_outs_vec[14] = PPG0_AND10_out[0];
assign PPG0_outs_vec[13] = PPG0_AND11_out[0];
assign PPG0_outs_vec[12] = PPG0_AND12_out[0];
assign PPG0_outs_vec[11] = PPG0_AND13_out[0];
assign PPG0_outs_vec[10] = PPG0_AND14_out[0];
assign PPG0_outs_vec[9] = PPG0_AND6_out[0];
assign PPG0_outs_vec[8] = PPG0_AND7_out[0];
assign PPG0_outs_vec[7] = PPG0_AND8_out[0];
assign PPG0_outs_vec[6] = PPG0_AND9_out[0];
assign PPG0_outs_vec[5] = PPG0_AND3_out[0];
assign PPG0_outs_vec[4] = PPG0_AND4_out[0];
assign PPG0_outs_vec[3] = PPG0_AND5_out[0];
assign PPG0_outs_vec[2] = PPG0_AND1_out[0];
assign PPG0_outs_vec[1] = PPG0_AND2_out[0];
assign PPG0_outs_vec[0] = PPG0_AND0_out[0];
assign CompressorTree0_outs_vec[28] = OutBits_ppg[63];
assign CompressorTree0_outs_vec[27] = CompressorTree0_FA8_cout[0];
assign CompressorTree0_outs_vec[26] = CompressorTree0_FA12_cout[0];
assign CompressorTree0_outs_vec[25] = CompressorTree0_FA8_sum[0];
assign CompressorTree0_outs_vec[24] = CompressorTree0_FA11_cout[0];
assign CompressorTree0_outs_vec[23] = CompressorTree0_FA12_sum[0];
assign CompressorTree0_outs_vec[22] = CompressorTree0_FA10_cout[0];
assign CompressorTree0_outs_vec[21] = CompressorTree0_FA11_sum[0];
assign CompressorTree0_outs_vec[20] = CompressorTree0_FA9_cout[0];
assign CompressorTree0_outs_vec[19] = CompressorTree0_FA10_sum[0];
assign CompressorTree0_outs_vec[18] = CompressorTree0_FA9_sum[0];
assign CompressorTree0_outs_vec[17] = CompressorTree0_FA5_sum[0];
assign CompressorTree0_outs_vec[16] = CompressorTree0_AC3211_out2[0];
assign CompressorTree0_outs_vec[15] = CompressorTree0_AC3211_out1[0];
assign CompressorTree0_outs_vec[14] = CompressorTree0_AC424_out2[0];
assign CompressorTree0_outs_vec[13] = CompressorTree0_AC424_out1[0];
assign CompressorTree0_outs_vec[12] = CompressorTree0_AC3210_out2[0];
assign CompressorTree0_outs_vec[11] = CompressorTree0_AC3210_out1[0];
assign CompressorTree0_outs_vec[10] = CompressorTree0_AC423_out2[0];
assign CompressorTree0_outs_vec[9] = CompressorTree0_AC423_out1[0];
assign CompressorTree0_outs_vec[8] = CompressorTree0_AC329_out2[0];
assign CompressorTree0_outs_vec[7] = CompressorTree0_AC329_out1[0];
assign CompressorTree0_outs_vec[6] = CompressorTree0_AC420_out1[0];
assign CompressorTree0_outs_vec[5] = CompressorTree0_AC420_out2[0];
assign CompressorTree0_outs_vec[4] = CompressorTree0_AC324_out1[0];
assign CompressorTree0_outs_vec[3] = CompressorTree0_AC324_out2[0];
assign CompressorTree0_outs_vec[2] = OutBits_ppg[2];
assign CompressorTree0_outs_vec[1] = OutBits_ppg[1];
assign CompressorTree0_outs_vec[0] = OutBits_ppg[0];



assign PPG0_AND0_out = (A[0] & B[0]);



assign PPG0_AND1_out = (A[1] & B[0]);



assign PPG0_AND2_out = (A[0] & B[1]);



assign PPG0_AND3_out = (A[2] & B[0]);



assign PPG0_AND4_out = (A[1] & B[1]);



assign PPG0_AND5_out = (A[0] & B[2]);



assign PPG0_AND6_out = (A[3] & B[0]);



assign PPG0_AND7_out = (A[2] & B[1]);



assign PPG0_AND8_out = (A[1] & B[2]);



assign PPG0_AND9_out = (A[0] & B[3]);



assign PPG0_AND10_out = (A[4] & B[0]);



assign PPG0_AND11_out = (A[3] & B[1]);



assign PPG0_AND12_out = (A[2] & B[2]);



assign PPG0_AND13_out = (A[1] & B[3]);



assign PPG0_AND14_out = (A[0] & B[4]);



assign PPG0_AND15_out = (A[5] & B[0]);



assign PPG0_AND16_out = (A[4] & B[1]);



assign PPG0_AND17_out = (A[3] & B[2]);



assign PPG0_AND18_out = (A[2] & B[3]);



assign PPG0_AND19_out = (A[1] & B[4]);



assign PPG0_AND20_out = (A[0] & B[5]);



assign PPG0_AND21_out = (A[6] & B[0]);



assign PPG0_AND22_out = (A[5] & B[1]);



assign PPG0_AND23_out = (A[4] & B[2]);



assign PPG0_AND24_out = (A[3] & B[3]);



assign PPG0_AND25_out = (A[2] & B[4]);



assign PPG0_AND26_out = (A[1] & B[5]);



assign PPG0_AND27_out = (A[0] & B[6]);



assign PPG0_AND28_out = (A[7] & B[0]);



assign PPG0_AND29_out = (A[6] & B[1]);



assign PPG0_AND30_out = (A[5] & B[2]);



assign PPG0_AND31_out = (A[4] & B[3]);



assign PPG0_AND32_out = (A[3] & B[4]);



assign PPG0_AND33_out = (A[2] & B[5]);



assign PPG0_AND34_out = (A[1] & B[6]);



assign PPG0_AND35_out = (A[0] & B[7]);



assign PPG0_AND36_out = (A[7] & B[1]);



assign PPG0_AND37_out = (A[6] & B[2]);



assign PPG0_AND38_out = (A[5] & B[3]);



assign PPG0_AND39_out = (A[4] & B[4]);



assign PPG0_AND40_out = (A[3] & B[5]);



assign PPG0_AND41_out = (A[2] & B[6]);



assign PPG0_AND42_out = (A[1] & B[7]);



assign PPG0_AND43_out = (A[7] & B[2]);



assign PPG0_AND44_out = (A[6] & B[3]);



assign PPG0_AND45_out = (A[5] & B[4]);



assign PPG0_AND46_out = (A[4] & B[5]);



assign PPG0_AND47_out = (A[3] & B[6]);



assign PPG0_AND48_out = (A[2] & B[7]);



assign PPG0_AND49_out = (A[7] & B[3]);



assign PPG0_AND50_out = (A[6] & B[4]);



assign PPG0_AND51_out = (A[5] & B[5]);



assign PPG0_AND52_out = (A[4] & B[6]);



assign PPG0_AND53_out = (A[3] & B[7]);



assign PPG0_AND54_out = (A[7] & B[4]);



assign PPG0_AND55_out = (A[6] & B[5]);



assign PPG0_AND56_out = (A[5] & B[6]);



assign PPG0_AND57_out = (A[4] & B[7]);



assign PPG0_AND58_out = (A[7] & B[5]);



assign PPG0_AND59_out = (A[6] & B[6]);



assign PPG0_AND60_out = (A[5] & B[7]);



assign PPG0_AND61_out = (A[7] & B[6]);



assign PPG0_AND62_out = (A[6] & B[7]);



assign PPG0_AND63_out = (A[7] & B[7]);



assign OutBits_ppg = PPG0_outs_vec;



assign CompressorTree0_AC320_out2 = ((OutBits_ppg[22] & OutBits_ppg[23]) | OutBits_ppg[24]);
assign CompressorTree0_AC320_out1 = (OutBits_ppg[22] | OutBits_ppg[23]);



assign CompressorTree0_AC321_out2 = ((OutBits_ppg[25] & OutBits_ppg[26]) | OutBits_ppg[27]);
assign CompressorTree0_AC321_out1 = (OutBits_ppg[25] | OutBits_ppg[26]);



assign CompressorTree0_AC322_out2 = ((OutBits_ppg[30] & OutBits_ppg[31]) | OutBits_ppg[32]);
assign CompressorTree0_AC322_out1 = (OutBits_ppg[30] | OutBits_ppg[31]);



assign CompressorTree0_AC323_out2 = ((OutBits_ppg[33] & OutBits_ppg[34]) | OutBits_ppg[35]);
assign CompressorTree0_AC323_out1 = (OutBits_ppg[33] | OutBits_ppg[34]);



assign CompressorTree0_FA0_sum = ((OutBits_ppg[37] ^ OutBits_ppg[38]) ^ OutBits_ppg[39]);
assign CompressorTree0_FA0_cout = (((OutBits_ppg[37] & OutBits_ppg[38]) | (OutBits_ppg[37] & OutBits_ppg[39])) | (OutBits_ppg[38] & OutBits_ppg[39]));



assign CompressorTree0_FA1_sum = ((OutBits_ppg[40] ^ OutBits_ppg[41]) ^ OutBits_ppg[42]);
assign CompressorTree0_FA1_cout = (((OutBits_ppg[40] & OutBits_ppg[41]) | (OutBits_ppg[40] & OutBits_ppg[42])) | (OutBits_ppg[41] & OutBits_ppg[42]));



assign CompressorTree0_FA2_sum = ((OutBits_ppg[51] ^ OutBits_ppg[52]) ^ OutBits_ppg[53]);
assign CompressorTree0_FA2_cout = (((OutBits_ppg[51] & OutBits_ppg[52]) | (OutBits_ppg[51] & OutBits_ppg[53])) | (OutBits_ppg[52] & OutBits_ppg[53]));



assign CompressorTree0_FA3_sum = ((OutBits_ppg[58] ^ OutBits_ppg[59]) ^ OutBits_ppg[60]);
assign CompressorTree0_FA3_cout = (((OutBits_ppg[58] & OutBits_ppg[59]) | (OutBits_ppg[58] & OutBits_ppg[60])) | (OutBits_ppg[59] & OutBits_ppg[60]));



assign CompressorTree0_AC324_out2 = ((OutBits_ppg[5] & OutBits_ppg[4]) | OutBits_ppg[3]);
assign CompressorTree0_AC324_out1 = (OutBits_ppg[5] | OutBits_ppg[4]);



assign CompressorTree0_AC420_out2 = (((OutBits_ppg[7] & OutBits_ppg[6]) | OutBits_ppg[9]) | OutBits_ppg[8]);
assign CompressorTree0_AC420_out1 = (((OutBits_ppg[9] & OutBits_ppg[8]) | OutBits_ppg[7]) | OutBits_ppg[6]);



assign CompressorTree0_AC421_out2 = (((OutBits_ppg[11] & OutBits_ppg[13]) | OutBits_ppg[14]) | OutBits_ppg[10]);
assign CompressorTree0_AC421_out1 = (((OutBits_ppg[14] & OutBits_ppg[10]) | OutBits_ppg[11]) | OutBits_ppg[13]);



assign CompressorTree0_AC325_out2 = ((OutBits_ppg[18] & OutBits_ppg[17]) | OutBits_ppg[19]);
assign CompressorTree0_AC325_out1 = (OutBits_ppg[18] | OutBits_ppg[17]);



assign CompressorTree0_AC326_out2 = ((OutBits_ppg[15] & OutBits_ppg[20]) | OutBits_ppg[16]);
assign CompressorTree0_AC326_out1 = (OutBits_ppg[15] | OutBits_ppg[20]);



assign CompressorTree0_AC422_out2 = (((OutBits_ppg[21] & CompressorTree0_AC320_out2) | CompressorTree0_AC321_out1) | CompressorTree0_AC321_out2);
assign CompressorTree0_AC422_out1 = (((CompressorTree0_AC321_out1 & CompressorTree0_AC321_out2) | OutBits_ppg[21]) | CompressorTree0_AC320_out2);



assign CompressorTree0_AC327_out2 = ((CompressorTree0_AC323_out2 & OutBits_ppg[29]) | OutBits_ppg[28]);
assign CompressorTree0_AC327_out1 = (CompressorTree0_AC323_out2 | OutBits_ppg[29]);



assign CompressorTree0_AC328_out2 = ((CompressorTree0_AC323_out1 & CompressorTree0_AC322_out1) | CompressorTree0_AC322_out2);
assign CompressorTree0_AC328_out1 = (CompressorTree0_AC323_out1 | CompressorTree0_AC322_out1);



assign CompressorTree0_FA4_sum = ((CompressorTree0_FA1_cout ^ OutBits_ppg[48]) ^ CompressorTree0_FA0_cout);
assign CompressorTree0_FA4_cout = (((CompressorTree0_FA1_cout & OutBits_ppg[48]) | (CompressorTree0_FA1_cout & CompressorTree0_FA0_cout)) | (OutBits_ppg[48] & CompressorTree0_FA0_cout));



assign CompressorTree0_FA5_sum = ((OutBits_ppg[43] ^ OutBits_ppg[47]) ^ OutBits_ppg[44]);
assign CompressorTree0_FA5_cout = (((OutBits_ppg[43] & OutBits_ppg[47]) | (OutBits_ppg[43] & OutBits_ppg[44])) | (OutBits_ppg[47] & OutBits_ppg[44]));



assign CompressorTree0_FA6_sum = ((CompressorTree0_FA2_sum ^ OutBits_ppg[50]) ^ OutBits_ppg[49]);
assign CompressorTree0_FA6_cout = (((CompressorTree0_FA2_sum & OutBits_ppg[50]) | (CompressorTree0_FA2_sum & OutBits_ppg[49])) | (OutBits_ppg[50] & OutBits_ppg[49]));



assign CompressorTree0_FA7_sum = ((OutBits_ppg[56] ^ OutBits_ppg[55]) ^ OutBits_ppg[57]);
assign CompressorTree0_FA7_cout = (((OutBits_ppg[56] & OutBits_ppg[55]) | (OutBits_ppg[56] & OutBits_ppg[57])) | (OutBits_ppg[55] & OutBits_ppg[57]));



assign CompressorTree0_HA0_sum = (CompressorTree0_FA2_cout ^ OutBits_ppg[54]);
assign CompressorTree0_HA0_cout = (CompressorTree0_FA2_cout & OutBits_ppg[54]);



assign CompressorTree0_FA8_sum = ((OutBits_ppg[62] ^ CompressorTree0_FA3_cout) ^ OutBits_ppg[61]);
assign CompressorTree0_FA8_cout = (((OutBits_ppg[62] & CompressorTree0_FA3_cout) | (OutBits_ppg[62] & OutBits_ppg[61])) | (CompressorTree0_FA3_cout & OutBits_ppg[61]));



assign CompressorTree0_AC329_out2 = ((CompressorTree0_AC421_out2 & OutBits_ppg[12]) | CompressorTree0_AC421_out1);
assign CompressorTree0_AC329_out1 = (CompressorTree0_AC421_out2 | OutBits_ppg[12]);



assign CompressorTree0_AC423_out2 = (((CompressorTree0_AC326_out2 & CompressorTree0_AC325_out2) | CompressorTree0_AC326_out1) | CompressorTree0_AC325_out1);
assign CompressorTree0_AC423_out1 = (((CompressorTree0_AC326_out1 & CompressorTree0_AC325_out1) | CompressorTree0_AC326_out2) | CompressorTree0_AC325_out2);



assign CompressorTree0_AC3210_out2 = ((CompressorTree0_AC422_out1 & CompressorTree0_AC422_out2) | CompressorTree0_AC320_out1);
assign CompressorTree0_AC3210_out1 = (CompressorTree0_AC422_out1 | CompressorTree0_AC422_out2);



assign CompressorTree0_AC424_out2 = (((CompressorTree0_AC327_out2 & CompressorTree0_AC328_out2) | CompressorTree0_AC328_out1) | CompressorTree0_AC327_out1);
assign CompressorTree0_AC424_out1 = (((CompressorTree0_AC328_out1 & CompressorTree0_AC327_out1) | CompressorTree0_AC327_out2) | CompressorTree0_AC328_out2);



assign CompressorTree0_AC3211_out2 = ((OutBits_ppg[36] & CompressorTree0_FA1_sum) | CompressorTree0_FA0_sum);
assign CompressorTree0_AC3211_out1 = (OutBits_ppg[36] | CompressorTree0_FA1_sum);



assign CompressorTree0_FA9_sum = ((CompressorTree0_FA4_sum ^ OutBits_ppg[46]) ^ OutBits_ppg[45]);
assign CompressorTree0_FA9_cout = (((CompressorTree0_FA4_sum & OutBits_ppg[46]) | (CompressorTree0_FA4_sum & OutBits_ppg[45])) | (OutBits_ppg[46] & OutBits_ppg[45]));



assign CompressorTree0_FA10_sum = ((CompressorTree0_FA6_sum ^ CompressorTree0_FA4_cout) ^ CompressorTree0_FA5_cout);
assign CompressorTree0_FA10_cout = (((CompressorTree0_FA6_sum & CompressorTree0_FA4_cout) | (CompressorTree0_FA6_sum & CompressorTree0_FA5_cout)) | (CompressorTree0_FA4_cout & CompressorTree0_FA5_cout));



assign CompressorTree0_FA11_sum = ((CompressorTree0_HA0_sum ^ CompressorTree0_FA7_sum) ^ CompressorTree0_FA6_cout);
assign CompressorTree0_FA11_cout = (((CompressorTree0_HA0_sum & CompressorTree0_FA7_sum) | (CompressorTree0_HA0_sum & CompressorTree0_FA6_cout)) | (CompressorTree0_FA7_sum & CompressorTree0_FA6_cout));



assign CompressorTree0_FA12_sum = ((CompressorTree0_FA7_cout ^ CompressorTree0_HA0_cout) ^ CompressorTree0_FA3_sum);
assign CompressorTree0_FA12_cout = (((CompressorTree0_FA7_cout & CompressorTree0_HA0_cout) | (CompressorTree0_FA7_cout & CompressorTree0_FA3_sum)) | (CompressorTree0_HA0_cout & CompressorTree0_FA3_sum));



assign OUTS = CompressorTree0_outs_vec;

endmodule
