// File: mux.v
// Generated by MyHDL 0.11
// Date: Tue Jul 27 17:45:35 2021


`timescale 1ns/10ps

module mux (
    z,
    a,
    b,
    sel
);


output z;
reg z;
input a;
input b;
input sel;




always @(b, a, sel) begin: MUX_COMB
    if ((sel == 1)) begin
        z = a;
    end
    else begin
        z = b;
    end
end

endmodule
