// File: PPG.v
// Generated by MyHDL 0.11
// Date: Sun Aug 15 14:44:51 2021


`timescale 1ns/10ps

module PPG (
    OUTS,
    A,
    B
);


output [63:0] OUTS;
wire [63:0] OUTS;
input [7:0] A;
input [7:0] B;

wire [63:0] outs_vec;
wire [0:0] AND0_out;
wire [0:0] AND1_out;
wire [0:0] AND2_out;
wire [0:0] AND3_out;
wire [0:0] AND4_out;
wire [0:0] AND5_out;
wire [0:0] AND6_out;
wire [0:0] AND7_out;
wire [0:0] AND8_out;
wire [0:0] AND9_out;
wire [0:0] AND10_out;
wire [0:0] AND11_out;
wire [0:0] AND12_out;
wire [0:0] AND13_out;
wire [0:0] AND14_out;
wire [0:0] AND15_out;
wire [0:0] AND16_out;
wire [0:0] AND17_out;
wire [0:0] AND18_out;
wire [0:0] AND19_out;
wire [0:0] AND20_out;
wire [0:0] AND21_out;
wire [0:0] AND22_out;
wire [0:0] AND23_out;
wire [0:0] AND24_out;
wire [0:0] AND25_out;
wire [0:0] AND26_out;
wire [0:0] AND27_out;
wire [0:0] AND28_out;
wire [0:0] AND29_out;
wire [0:0] AND30_out;
wire [0:0] AND31_out;
wire [0:0] AND32_out;
wire [0:0] AND33_out;
wire [0:0] AND34_out;
wire [0:0] AND35_out;
wire [0:0] AND36_out;
wire [0:0] AND37_out;
wire [0:0] AND38_out;
wire [0:0] AND39_out;
wire [0:0] AND40_out;
wire [0:0] AND41_out;
wire [0:0] AND42_out;
wire [0:0] AND43_out;
wire [0:0] AND44_out;
wire [0:0] AND45_out;
wire [0:0] AND46_out;
wire [0:0] AND47_out;
wire [0:0] AND48_out;
wire [0:0] AND49_out;
wire [0:0] AND50_out;
wire [0:0] AND51_out;
wire [0:0] AND52_out;
wire [0:0] AND53_out;
wire [0:0] AND54_out;
wire [0:0] AND55_out;
wire [0:0] AND56_out;
wire [0:0] AND57_out;
wire [0:0] AND58_out;
wire [0:0] AND59_out;
wire [0:0] AND60_out;
wire [0:0] AND61_out;
wire [0:0] AND62_out;
wire [0:0] AND63_out;

assign outs_vec[63] = AND63_out[0];
assign outs_vec[62] = AND61_out[0];
assign outs_vec[61] = AND62_out[0];
assign outs_vec[60] = AND58_out[0];
assign outs_vec[59] = AND59_out[0];
assign outs_vec[58] = AND60_out[0];
assign outs_vec[57] = AND54_out[0];
assign outs_vec[56] = AND55_out[0];
assign outs_vec[55] = AND56_out[0];
assign outs_vec[54] = AND57_out[0];
assign outs_vec[53] = AND49_out[0];
assign outs_vec[52] = AND50_out[0];
assign outs_vec[51] = AND51_out[0];
assign outs_vec[50] = AND52_out[0];
assign outs_vec[49] = AND53_out[0];
assign outs_vec[48] = AND43_out[0];
assign outs_vec[47] = AND44_out[0];
assign outs_vec[46] = AND45_out[0];
assign outs_vec[45] = AND46_out[0];
assign outs_vec[44] = AND47_out[0];
assign outs_vec[43] = AND48_out[0];
assign outs_vec[42] = AND36_out[0];
assign outs_vec[41] = AND37_out[0];
assign outs_vec[40] = AND38_out[0];
assign outs_vec[39] = AND39_out[0];
assign outs_vec[38] = AND40_out[0];
assign outs_vec[37] = AND41_out[0];
assign outs_vec[36] = AND42_out[0];
assign outs_vec[35] = AND28_out[0];
assign outs_vec[34] = AND29_out[0];
assign outs_vec[33] = AND30_out[0];
assign outs_vec[32] = AND31_out[0];
assign outs_vec[31] = AND32_out[0];
assign outs_vec[30] = AND33_out[0];
assign outs_vec[29] = AND34_out[0];
assign outs_vec[28] = AND35_out[0];
assign outs_vec[27] = AND21_out[0];
assign outs_vec[26] = AND22_out[0];
assign outs_vec[25] = AND23_out[0];
assign outs_vec[24] = AND24_out[0];
assign outs_vec[23] = AND25_out[0];
assign outs_vec[22] = AND26_out[0];
assign outs_vec[21] = AND27_out[0];
assign outs_vec[20] = AND15_out[0];
assign outs_vec[19] = AND16_out[0];
assign outs_vec[18] = AND17_out[0];
assign outs_vec[17] = AND18_out[0];
assign outs_vec[16] = AND19_out[0];
assign outs_vec[15] = AND20_out[0];
assign outs_vec[14] = AND10_out[0];
assign outs_vec[13] = AND11_out[0];
assign outs_vec[12] = AND12_out[0];
assign outs_vec[11] = AND13_out[0];
assign outs_vec[10] = AND14_out[0];
assign outs_vec[9] = AND6_out[0];
assign outs_vec[8] = AND7_out[0];
assign outs_vec[7] = AND8_out[0];
assign outs_vec[6] = AND9_out[0];
assign outs_vec[5] = AND3_out[0];
assign outs_vec[4] = AND4_out[0];
assign outs_vec[3] = AND5_out[0];
assign outs_vec[2] = AND1_out[0];
assign outs_vec[1] = AND2_out[0];
assign outs_vec[0] = AND0_out[0];



assign AND0_out = (A[0] & B[0]);



assign AND1_out = (A[1] & B[0]);



assign AND2_out = (A[0] & B[1]);



assign AND3_out = (A[2] & B[0]);



assign AND4_out = (A[1] & B[1]);



assign AND5_out = (A[0] & B[2]);



assign AND6_out = (A[3] & B[0]);



assign AND7_out = (A[2] & B[1]);



assign AND8_out = (A[1] & B[2]);



assign AND9_out = (A[0] & B[3]);



assign AND10_out = (A[4] & B[0]);



assign AND11_out = (A[3] & B[1]);



assign AND12_out = (A[2] & B[2]);



assign AND13_out = (A[1] & B[3]);



assign AND14_out = (A[0] & B[4]);



assign AND15_out = (A[5] & B[0]);



assign AND16_out = (A[4] & B[1]);



assign AND17_out = (A[3] & B[2]);



assign AND18_out = (A[2] & B[3]);



assign AND19_out = (A[1] & B[4]);



assign AND20_out = (A[0] & B[5]);



assign AND21_out = (A[6] & B[0]);



assign AND22_out = (A[5] & B[1]);



assign AND23_out = (A[4] & B[2]);



assign AND24_out = (A[3] & B[3]);



assign AND25_out = (A[2] & B[4]);



assign AND26_out = (A[1] & B[5]);



assign AND27_out = (A[0] & B[6]);



assign AND28_out = (A[7] & B[0]);



assign AND29_out = (A[6] & B[1]);



assign AND30_out = (A[5] & B[2]);



assign AND31_out = (A[4] & B[3]);



assign AND32_out = (A[3] & B[4]);



assign AND33_out = (A[2] & B[5]);



assign AND34_out = (A[1] & B[6]);



assign AND35_out = (A[0] & B[7]);



assign AND36_out = (A[7] & B[1]);



assign AND37_out = (A[6] & B[2]);



assign AND38_out = (A[5] & B[3]);



assign AND39_out = (A[4] & B[4]);



assign AND40_out = (A[3] & B[5]);



assign AND41_out = (A[2] & B[6]);



assign AND42_out = (A[1] & B[7]);



assign AND43_out = (A[7] & B[2]);



assign AND44_out = (A[6] & B[3]);



assign AND45_out = (A[5] & B[4]);



assign AND46_out = (A[4] & B[5]);



assign AND47_out = (A[3] & B[6]);



assign AND48_out = (A[2] & B[7]);



assign AND49_out = (A[7] & B[3]);



assign AND50_out = (A[6] & B[4]);



assign AND51_out = (A[5] & B[5]);



assign AND52_out = (A[4] & B[6]);



assign AND53_out = (A[3] & B[7]);



assign AND54_out = (A[7] & B[4]);



assign AND55_out = (A[6] & B[5]);



assign AND56_out = (A[5] & B[6]);



assign AND57_out = (A[4] & B[7]);



assign AND58_out = (A[7] & B[5]);



assign AND59_out = (A[6] & B[6]);



assign AND60_out = (A[5] & B[7]);



assign AND61_out = (A[7] & B[6]);



assign AND62_out = (A[6] & B[7]);



assign AND63_out = (A[7] & B[7]);



assign OUTS = outs_vec;

endmodule
